In [1]:
!pip install -q ultralytics onnx onnxsim

import json, os, shutil, random, yaml
from pathlib import Path
from collections import defaultdict, Counter
from ultralytics import YOLO

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.8/41.8 kB 2.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 31.8 MB/s eta 0:00:0000:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.9 MB 88.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.2/12.2 MB 102.4 MB/s eta 0:00:0000:010:01
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
dask-cuda 26.2.0 requires cuda-core==0.3.*, but you have cuda-core 1.0.1 which is incompatible.
dask-cuda 26.2.0 requires numba-cuda<0.23.0,>=0.22.1, but you have numba-cuda 0.30.2 which is incompatible.
distributed-ucxx-cu12 0.48.0 requires numba-cuda[cu12]<0.23.0,>=0.22.1, but you have numba-cuda 0.30.2 which is incompatible.
cuml-cu12 26.2.0 requires numba<0.62.0,>=0.60.0, but you have numba 0.65.1 which is incompatible.
cuml-cu12 26.2.0 requires numba-cuda[cu12]<0.23.0,>=0.22.1, but you have numba-cuda 0.30.2 which is incompatible.
ucxx-cu12 0.48.0 requires numba-cuda[cu12]<0.23.0,>=0.22.1, but you have numba-cuda 0.30.2 which is incompatible.
cudf-cu12 26.2.1 requires numba<0.62.0,>=0.60.0, but you have numba 0.65.1 which is incompatible.
cudf-cu12 26.2.1 requires numba-cuda[cu12]<0.23.0,>=0.22.2, but you have numba-cuda 0.30.2 which is incompatible.
Creating new Ultralytics Settings v0.0.6 file ✅
View Ultralytics Settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/quickstart/#ultralytics-settings.

In [3]:
BASE = "/kaggle/input/datasets/truthisneverlinear/dentex-challenge-2023/training_data/training_data/quadrant-enumeration-disease"

JSON_PATH = f"{BASE}/train_quadrant_enumeration_disease.json"
IMG_SRC = f"{BASE}/xrays"

WORK = "/kaggle/working"
FDI_OUT = f"{WORK}/dentex_fdi_yolo"
DISEASE_OUT = f"{WORK}/dentex_disease_yolo"

print(os.path.exists(JSON_PATH), JSON_PATH)
print(os.path.exists(IMG_SRC), IMG_SRC)

True /kaggle/input/datasets/truthisneverlinear/dentex-challenge-2023/training_data/training_data/quadrant-enumeration-disease/train_quadrant_enumeration_disease.json
True /kaggle/input/datasets/truthisneverlinear/dentex-challenge-2023/training_data/training_data/quadrant-enumeration-disease/xrays

In [4]:
with open(JSON_PATH) as f:
    data = json.load(f)

print(data.keys())
print("Images:", len(data["images"]))
print("Annotations:", len(data["annotations"]))
print("Esempio annotation:")
print(data["annotations"][0])

dict_keys(['images', 'annotations', 'categories_1', 'categories_2', 'categories_3'])
Images: 705
Annotations: 3529
Esempio annotation:
{'iscrowd': 0, 'image_id': 1, 'bbox': [542.0, 698.0, 220.0, 271.0], 'segmentation': [[621, 703, 573, 744, 542, 885, 580, 945, 650, 969, 711, 883, 762, 807, 748, 741, 649, 698]], 'id': 1, 'area': 39683, 'category_id_1': 3, 'category_id_2': 7, 'category_id_3': 0}

In [5]:
images = {img["id"]: img for img in data["images"]}

anns_by_image = defaultdict(list)
for ann in data["annotations"]:
    anns_by_image[ann["image_id"]].append(ann)

random.seed(42)
all_ids = list(images.keys())
random.shuffle(all_ids)

cut = int(len(all_ids) * 0.9)
train_ids = set(all_ids[:cut])
val_ids = set(all_ids[cut:])

print("Train:", len(train_ids))
print("Val:", len(val_ids))

Train: 634
Val: 71

In [6]:
# FDI permanenti: 11-18, 21-28, 31-38, 41-48
fdi_list = []
for q in [1, 2, 3, 4]:
    for t in [1, 2, 3, 4, 5, 6, 7, 8]:
        fdi_list.append(f"{q}{t}")

fdi_to_class = {fdi: idx for idx, fdi in enumerate(fdi_list)}
class_to_fdi = {idx: fdi for fdi, idx in fdi_to_class.items()}

print(class_to_fdi)

{0: '11', 1: '12', 2: '13', 3: '14', 4: '15', 5: '16', 6: '17', 7: '18', 8: '21', 9: '22', 10: '23', 11: '24', 12: '25', 13: '26', 14: '27', 15: '28', 16: '31', 17: '32', 18: '33', 19: '34', 20: '35', 21: '36', 22: '37', 23: '38', 24: '41', 25: '42', 26: '43', 27: '44', 28: '45', 29: '46', 30: '47', 31: '48'}

In [7]:
shutil.rmtree(FDI_OUT, ignore_errors=True)

for split in ["train", "val"]:
    Path(f"{FDI_OUT}/images/{split}").mkdir(parents=True, exist_ok=True)
    Path(f"{FDI_OUT}/labels/{split}").mkdir(parents=True, exist_ok=True)

for img_id, info in images.items():
    split = "train" if img_id in train_ids else "val"

    filename = info["file_name"]
    img_w = info["width"]
    img_h = info["height"]

    shutil.copy2(f"{IMG_SRC}/{filename}", f"{FDI_OUT}/images/{split}/{filename}")

    label_path = f"{FDI_OUT}/labels/{split}/{Path(filename).stem}.txt"

    with open(label_path, "w") as lf:
        for ann in anns_by_image[img_id]:
            quadrant = ann["category_id_1"] + 1
            tooth_number = ann["category_id_2"] + 1
            fdi = f"{quadrant}{tooth_number}"

            if fdi not in fdi_to_class:
                continue

            cls = fdi_to_class[fdi]

            x, y, w, h = ann["bbox"]

            xc = (x + w / 2) / img_w
            yc = (y + h / 2) / img_h
            wn = w / img_w
            hn = h / img_h

            lf.write(f"{cls} {xc:.6f} {yc:.6f} {wn:.6f} {hn:.6f}\n")

print("Dataset FDI creato:", FDI_OUT)

Dataset FDI creato: /kaggle/working/dentex_fdi_yolo

In [7]:
fdi_yaml = {
    "path": FDI_OUT,
    "train": "images/train",
    "val": "images/val",
    "names": class_to_fdi
}

with open(f"{WORK}/fdi.yaml", "w") as f:
    yaml.dump(fdi_yaml, f, sort_keys=False)

print(open(f"{WORK}/fdi.yaml").read())

path: /kaggle/working/dentex_fdi_yolo
train: images/train
val: images/val
names:
  0: '11'
  1: '12'
  2: '13'
  3: '14'
  4: '15'
  5: '16'
  6: '17'
  7: '18'
  8: '21'
  9: '22'
  10: '23'
  11: '24'
  12: '25'
  13: '26'
  14: '27'
  15: '28'
  16: '31'
  17: '32'
  18: '33'
  19: '34'
  20: '35'
  21: '36'
  22: '37'
  23: '38'
  24: '41'
  25: '42'
  26: '43'
  27: '44'
  28: '45'
  29: '46'
  30: '47'
  31: '48'

In [8]:
# Mapping DentalCare:
# 0 -> Impacted
# 1 -> Caries
# 2 -> Periapical_Lesion
# 3 -> Deep_Caries

disease_names = {
    0: "Impacted",
    1: "Caries",
    2: "Periapical_Lesion",
    3: "Deep_Caries"
}

print("Disease category counts:")
print(Counter([ann["category_id_3"] for ann in data["annotations"]]))

shutil.rmtree(DISEASE_OUT, ignore_errors=True)

for split in ["train", "val"]:
    Path(f"{DISEASE_OUT}/images/{split}").mkdir(parents=True, exist_ok=True)
    Path(f"{DISEASE_OUT}/labels/{split}").mkdir(parents=True, exist_ok=True)

for img_id, info in images.items():
    split = "train" if img_id in train_ids else "val"

    filename = info["file_name"]
    img_w = info["width"]
    img_h = info["height"]

    shutil.copy2(f"{IMG_SRC}/{filename}", f"{DISEASE_OUT}/images/{split}/{filename}")

    label_path = f"{DISEASE_OUT}/labels/{split}/{Path(filename).stem}.txt"

    with open(label_path, "w") as lf:
        for ann in anns_by_image[img_id]:
            cls = ann["category_id_3"]

            x, y, w, h = ann["bbox"]

            xc = (x + w / 2) / img_w
            yc = (y + h / 2) / img_h
            wn = w / img_w
            hn = h / img_h

            lf.write(f"{cls} {xc:.6f} {yc:.6f} {wn:.6f} {hn:.6f}\n")

print("Dataset disease creato:", DISEASE_OUT)

Disease category counts:
Counter({1: 2189, 0: 604, 3: 578, 2: 158})
Dataset disease creato: /kaggle/working/dentex_disease_yolo

In [9]:
disease_yaml = {
    "path": DISEASE_OUT,
    "train": "images/train",
    "val": "images/val",
    "names": disease_names
}

with open(f"{WORK}/disease.yaml", "w") as f:
    yaml.dump(disease_yaml, f, sort_keys=False)

print(open(f"{WORK}/disease.yaml").read())

path: /kaggle/working/dentex_disease_yolo
train: images/train
val: images/val
names:
  0: Impacted
  1: Caries
  2: Periapical_Lesion
  3: Deep_Caries

In [10]:
print("FDI train images:", len(list(Path(f"{FDI_OUT}/images/train").glob("*"))))
print("FDI val images:", len(list(Path(f"{FDI_OUT}/images/val").glob("*"))))
print("Disease train images:", len(list(Path(f"{DISEASE_OUT}/images/train").glob("*"))))
print("Disease val images:", len(list(Path(f"{DISEASE_OUT}/images/val").glob("*"))))

print("Esempio label FDI:")
print(list(Path(f"{FDI_OUT}/labels/train").glob("*.txt"))[0].read_text()[:500])

print("Esempio label disease:")
print(list(Path(f"{DISEASE_OUT}/labels/train").glob("*.txt"))[0].read_text()[:500])

FDI train images: 634
FDI val images: 71
Disease train images: 634
Disease val images: 71
Esempio label FDI:
3 0.405999 0.400180 0.033788 0.323294
4 0.381136 0.398107 0.029963 0.313623
5 0.354998 0.405015 0.041438 0.261122
6 0.316110 0.398798 0.042713 0.218292
11 0.587690 0.418831 0.035063 0.291517
22 0.694457 0.608352 0.080358 0.211868
28 0.387616 0.680768 0.042268 0.237332
30 0.313407 0.626119 0.083095 0.202981
31 0.277863 0.572511 0.085977 0.168631
22 0.688464 0.601824 0.067672 0.199088

Esempio label disease:
3 0.405999 0.400180 0.033788 0.323294
3 0.381136 0.398107 0.029963 0.313623
1 0.354998 0.405015 0.041438 0.261122
1 0.316110 0.398798 0.042713 0.218292
3 0.587690 0.418831 0.035063 0.291517
2 0.694457 0.608352 0.080358 0.211868
1 0.387616 0.680768 0.042268 0.237332
3 0.313407 0.626119 0.083095 0.202981
1 0.277863 0.572511 0.085977 0.168631
3 0.688464 0.601824 0.067672 0.199088

In [15]:
model_fdi = YOLO("yolov8l.pt")

model_fdi.train(
    data=f"{WORK}/fdi.yaml",
    epochs=100,
    imgsz=1024,
    batch=4,
    project=f"{WORK}/runs",
    name="dentex_fdi_v1",
    patience=20,
    workers=2
)

Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolov8l.pt to 'yolov8l.pt': 100% ━━━━━━━━━━━━ 83.7MB 244.5MB/s 0.3s0.3s<0.0s
Ultralytics 8.4.83 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=4, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/working/fdi.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dis=6.0, distill_model=None, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=100, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=1024, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8l.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=dentex_fdi_v1-2, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=20, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/kaggle/working/runs, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/kaggle/working/runs/dentex_fdi_v1-2, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=2, workspace=None
Overriding model.yaml nc=80 with nc=32

                   from  n    params  module                                       arguments
  0                  -1  1      1856  ultralytics.nn.modules.conv.Conv             [3, 64, 3, 2]
  1                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  2                  -1  3    279808  ultralytics.nn.modules.block.C2f             [128, 128, 3, True]
  3                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  4                  -1  6   2101248  ultralytics.nn.modules.block.C2f             [256, 256, 6, True]
  5                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  6                  -1  6   8396800  ultralytics.nn.modules.block.C2f             [512, 512, 6, True]
  7                  -1  1   2360320  ultralytics.nn.modules.conv.Conv             [512, 512, 3, 2]
  8                  -1  3   4461568  ultralytics.nn.modules.block.C2f             [512, 512, 3, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  3   4723712  ultralytics.nn.modules.block.C2f             [1024, 512, 3]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  3   1247744  ultralytics.nn.modules.block.C2f             [768, 256, 3]
 16                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  3   4592640  ultralytics.nn.modules.block.C2f             [768, 512, 3]
 19                  -1  1   2360320  ultralytics.nn.modules.conv.Conv             [512, 512, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  3   4723712  ultralytics.nn.modules.block.C2f             [1024, 512, 3]
 22        [15, 18, 21]  1   5607472  ultralytics.nn.modules.head.Detect           [32, 16, None, [256, 512, 512]]
Model summary: 210 layers, 43,654,512 parameters, 43,654,496 gradients, 165.5 GFLOPs

Transferred 589/595 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 5402.7±1131.0 MB/s, size: 3745.0 KB)
train: Scanning /kaggle/working/dentex_fdi_yolo/labels/train.cache... 634 images, 23 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 634/634 295.5Mit/s 0.0s
train: /kaggle/working/dentex_fdi_yolo/images/train/train_280.png: 1 duplicate labels removed
train: /kaggle/working/dentex_fdi_yolo/images/train/train_377.png: 1 duplicate labels removed
train: /kaggle/working/dentex_fdi_yolo/images/train/train_481.png: 1 duplicate labels removed
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 2175.1±2082.6 MB/s, size: 3733.4 KB)
val: Scanning /kaggle/working/dentex_fdi_yolo/labels/val.cache... 71 images, 4 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 71/71 2.1Mit/s 0.0s
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.000278, momentum=0.9) with parameter groups 97 weight(decay=0.0), 104 weight(decay=0.0005), 103 bias(decay=0.0)
Plotting labels to /kaggle/working/runs/dentex_fdi_v1-2/labels.jpg...
Image sizes 1024 train, 1024 val
Using 2 dataloader workers
Logging results to /kaggle/working/runs/dentex_fdi_v1-2
Starting training for 100 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      1/100      6.73G      1.387      3.745      1.469         10       1024: 100% ━━━━━━━━━━━━ 159/159 1.7it/s 1:340.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 4.2it/s 2.2s0.3s
                   all         71        363      0.495       0.33      0.132     0.0901

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      2/100      6.97G      1.131       2.55      1.301         11       1024: 100% ━━━━━━━━━━━━ 159/159 1.8it/s 1:310.4sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 4.2it/s 2.2s0.3s
                   all         71        363      0.497      0.305      0.173      0.121

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      3/100      6.97G      1.131      2.357       1.31         20       1024: 100% ━━━━━━━━━━━━ 159/159 1.8it/s 1:300.4sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 4.2it/s 2.1s0.3s
                   all         71        363      0.471      0.349      0.193      0.131

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      4/100      6.97G      1.109      2.208      1.305         14       1024: 100% ━━━━━━━━━━━━ 159/159 1.8it/s 1:300.4sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 4.2it/s 2.2s0.3s
                   all         71        363      0.482      0.374      0.208      0.141

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      5/100      6.97G      1.092      2.097      1.311         12       1024: 100% ━━━━━━━━━━━━ 159/159 1.8it/s 1:300.4sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 4.2it/s 2.1s0.3s
                   all         71        363       0.49      0.315      0.214      0.149

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      6/100      6.97G      1.049      2.008      1.282         21       1024: 100% ━━━━━━━━━━━━ 159/159 1.8it/s 1:300.4sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 4.2it/s 2.2s0.3s
                   all         71        363      0.431      0.381       0.23      0.162

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      7/100      6.97G      1.056      1.916      1.293         14       1024: 100% ━━━━━━━━━━━━ 159/159 1.8it/s 1:300.4sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 4.2it/s 2.1s0.3s
                   all         71        363      0.542      0.351      0.231       0.16

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      8/100      6.97G      1.036      1.814      1.272         13       1024: 100% ━━━━━━━━━━━━ 159/159 1.8it/s 1:300.4sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 4.3it/s 2.1s0.3s
                   all         71        363       0.42      0.374      0.272      0.192

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      9/100      6.97G      1.019      1.757      1.272         15       1024: 100% ━━━━━━━━━━━━ 159/159 1.8it/s 1:300.4sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 4.2it/s 2.1s0.3s
                   all         71        363      0.325      0.466      0.244      0.174

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     10/100      6.97G      1.007      1.757      1.273         42       1024: 100% ━━━━━━━━━━━━ 159/159 1.8it/s 1:300.4sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 4.2it/s 2.2s0.3s
                   all         71        363      0.439       0.37       0.27      0.192

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     11/100      6.97G      0.991      1.701      1.246         14       1024: 100% ━━━━━━━━━━━━ 159/159 1.8it/s 1:300.4sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 4.2it/s 2.1s0.3s
                   all         71        363      0.341      0.477      0.294      0.212

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     12/100      6.97G     0.9757       1.64      1.246         12       1024: 100% ━━━━━━━━━━━━ 159/159 1.8it/s 1:300.4sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 4.2it/s 2.2s0.3s
                   all         71        363      0.394      0.435       0.29      0.201

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     13/100      6.97G     0.9763       1.62      1.258          9       1024: 100% ━━━━━━━━━━━━ 159/159 1.8it/s 1:300.4sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 4.2it/s 2.2s0.3s
                   all         71        363      0.328       0.43      0.286      0.209

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     14/100      6.97G     0.9515      1.583      1.232         23       1024: 100% ━━━━━━━━━━━━ 159/159 1.8it/s 1:300.4sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 4.2it/s 2.1s0.3s
                   all         71        363      0.433      0.458      0.293      0.211

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     15/100      6.97G     0.9664      1.585      1.239         25       1024: 100% ━━━━━━━━━━━━ 159/159 1.8it/s 1:300.4sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 4.2it/s 2.1s0.3s
                   all         71        363      0.445      0.352      0.293      0.208

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     16/100      6.97G     0.9182      1.517      1.218          7       1024: 100% ━━━━━━━━━━━━ 159/159 1.8it/s 1:300.4sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 4.3it/s 2.1s0.3s
                   all         71        363      0.428      0.354      0.307      0.222

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     17/100      6.97G     0.9207      1.488      1.219         15       1024: 100% ━━━━━━━━━━━━ 159/159 1.8it/s 1:300.4sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 4.2it/s 2.1s0.3s
                   all         71        363      0.375      0.426      0.293      0.205

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     18/100      6.97G     0.9032      1.463      1.192          9       1024: 100% ━━━━━━━━━━━━ 159/159 1.8it/s 1:300.5sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 4.2it/s 2.1s0.3s
                   all         71        363      0.378      0.457      0.309      0.216

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     19/100      6.97G     0.8892      1.436      1.192         24       1024: 100% ━━━━━━━━━━━━ 159/159 1.8it/s 1:300.4sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 4.2it/s 2.2s0.3s
                   all         71        363      0.385      0.372      0.289      0.207

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     20/100      6.97G     0.8896      1.398      1.195         25       1024: 100% ━━━━━━━━━━━━ 159/159 1.8it/s 1:300.4sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 4.2it/s 2.1s0.3s
                   all         71        363      0.434      0.355      0.298      0.211

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     21/100      6.97G     0.8877      1.335      1.181         14       1024: 100% ━━━━━━━━━━━━ 159/159 1.8it/s 1:300.4sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 4.2it/s 2.1s0.3s
                   all         71        363      0.361      0.435       0.33      0.235

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     22/100      6.97G     0.8934      1.281      1.207         21       1024: 100% ━━━━━━━━━━━━ 159/159 1.8it/s 1:300.4sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 4.1it/s 2.2s0.3s
                   all         71        363      0.551      0.333      0.368      0.265

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     23/100      6.97G     0.8515       1.19      1.171         15       1024: 100% ━━━━━━━━━━━━ 159/159 1.8it/s 1:300.4sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 4.2it/s 2.1s0.3s
                   all         71        363      0.458      0.472      0.451      0.322

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     24/100      6.97G     0.8458      1.181      1.156         28       1024: 100% ━━━━━━━━━━━━ 159/159 1.8it/s 1:300.4sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 4.2it/s 2.1s0.3s
                   all         71        363      0.555      0.396      0.426      0.298

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     25/100      6.97G      0.837       1.09      1.156         21       1024: 100% ━━━━━━━━━━━━ 159/159 1.8it/s 1:300.4sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 4.3it/s 2.1s0.2s
                   all         71        363      0.373      0.484      0.425      0.307

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     26/100      6.97G      0.821      1.094      1.143         15       1024: 100% ━━━━━━━━━━━━ 159/159 1.8it/s 1:300.4sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 4.2it/s 2.1s0.3s
                   all         71        363      0.554      0.383       0.42      0.294

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     27/100      6.97G     0.8208      1.036      1.147         14       1024: 100% ━━━━━━━━━━━━ 159/159 1.8it/s 1:300.4sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 4.3it/s 2.1s0.3s
                   all         71        363      0.544      0.389      0.438      0.308

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     28/100      6.97G     0.8005      0.981      1.138         21       1024: 100% ━━━━━━━━━━━━ 159/159 1.8it/s 1:300.4sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 4.2it/s 2.1s0.3s
                   all         71        363      0.336      0.437      0.394      0.271

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     29/100      6.97G     0.8068      1.005      1.126         26       1024: 100% ━━━━━━━━━━━━ 159/159 1.8it/s 1:300.4sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 4.2it/s 2.2s0.3s
                   all         71        363      0.651      0.391      0.412       0.29

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     30/100      6.97G     0.7849     0.9639      1.125         35       1024: 100% ━━━━━━━━━━━━ 159/159 1.8it/s 1:300.4sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 4.3it/s 2.1s0.2s
                   all         71        363      0.504      0.394      0.438      0.307

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     31/100      6.97G      0.778     0.9139      1.115         26       1024: 100% ━━━━━━━━━━━━ 159/159 1.8it/s 1:300.4sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 4.2it/s 2.2s0.3s
                   all         71        363      0.388      0.391      0.405      0.286

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     32/100      6.97G     0.7731     0.8994      1.115          8       1024: 100% ━━━━━━━━━━━━ 159/159 1.8it/s 1:300.4sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 4.2it/s 2.1s0.3s
                   all         71        363      0.486      0.391      0.421      0.291

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     33/100      6.97G     0.7424     0.8499      1.088         10       1024: 100% ━━━━━━━━━━━━ 159/159 1.8it/s 1:300.4sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 4.2it/s 2.1s0.3s
                   all         71        363      0.496       0.44       0.42      0.297

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

ultralytics.utils.metrics.DetMetrics object with attributes:

ap_class_index: array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 18, 19, 20, 21, 22, 23, 25, 26, 27, 28, 29, 30, 31])
box: ultralytics.utils.metrics.Metric object
confusion_matrix: <ultralytics.utils.metrics.ConfusionMatrix object at 0x7f5fb50dbbc0>
curves: ['Precision-Recall(B)', 'F1-Confidence(B)', 'Precision-Confidence(B)', 'Recall-Confidence(B)']
curves_results: [[array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,
           0.33634,     0.33734,     0.33834,     0.33934,     0.34034,     0.34134,     0.34234,     0.34334,     0.34434,     0.34535,     0.34635,     0.34735,     0.34835,     0.34935,     0.35035,     0.35135,     0.35235,     0.35335,     0.35435,     0.35536,     0.35636,     0.35736,     0.35836,     0.35936,
           0.36036,     0.36136,     0.36236,     0.36336,     0.36436,     0.36537,     0.36637,     0.36737,     0.36837,     0.36937,     0.37037,     0.37137,     0.37237,     0.37337,     0.37437,     0.37538,     0.37638,     0.37738,     0.37838,     0.37938,     0.38038,     0.38138,     0.38238,     0.38338,
           0.38438,     0.38539,     0.38639,     0.38739,     0.38839,     0.38939,     0.39039,     0.39139,     0.39239,     0.39339,     0.39439,      0.3954,      0.3964,      0.3974,      0.3984,      0.3994,      0.4004,      0.4014,      0.4024,      0.4034,      0.4044,     0.40541,     0.40641,     0.40741,
           0.40841,     0.40941,     0.41041,     0.41141,     0.41241,     0.41341,     0.41441,     0.41542,     0.41642,     0.41742,     0.41842,     0.41942,     0.42042,     0.42142,     0.42242,     0.42342,     0.42442,     0.42543,     0.42643,     0.42743,     0.42843,     0.42943,     0.43043,     0.43143,
           0.43243,     0.43343,     0.43443,     0.43544,     0.43644,     0.43744,     0.43844,     0.43944,     0.44044,     0.44144,     0.44244,     0.44344,     0.44444,     0.44545,     0.44645,     0.44745,     0.44845,     0.44945,     0.45045,     0.45145,     0.45245,     0.45345,     0.45445,     0.45546,
           0.45646,     0.45746,     0.45846,     0.45946,     0.46046,     0.46146,     0.46246,     0.46346,     0.46446,     0.46547,     0.46647,     0.46747,     0.46847,     0.46947,     0.47047,     0.47147,     0.47247,     0.47347,     0.47447,     0.47548,     0.47648,     0.47748,     0.47848,     0.47948,
           0.48048,     0.48148,     0.48248,     0.48348,     0.48448,     0.48549,     0.48649,     0.48749,     0.48849,     0.48949,     0.49049,     0.49149,     0.49249,     0.49349,     0.49449,      0.4955,      0.4965,      0.4975,      0.4985,      0.4995,      0.5005,      0.5015,      0.5025,      0.5035,
            0.5045,     0.50551,     0.50651,     0.50751,     0.50851,     0.50951,     0.51051,     0.51151,     0.51251,     0.51351,     0.51451,     0.51552,     0.51652,     0.51752,     0.51852,     0.51952,     0.52052,     0.52152,     0.52252,     0.52352,     0.52452,     0.52553,     0.52653,     0.52753,
           0.52853,     0.52953,     0.53053,     0.53153,     0.53253,     0.53353,     0.53453,     0.53554,     0.53654,     0.53754,     0.53854,     0.53954,     0.54054,     0.54154,     0.54254,     0.54354,     0.54454,     0.54555,     0.54655,     0.54755,     0.54855,     0.54955,     0.55055,     0.55155,
           0.55255,     0.55355,     0.55455,     0.55556,     0.55656,     0.55756,     0.55856,     0.55956,     0.56056,     0.56156,     0.56256,     0.56356,     0.56456,     0.56557,     0.56657,     0.56757,     0.56857,     0.56957,     0.57057,     0.57157,     0.57257,     0.57357,     0.57457,     0.57558,
           0.57658,     0.57758,     0.57858,     0.57958,     0.58058,     0.58158,     0.58258,     0.58358,     0.58458,     0.58559,     0.58659,     0.58759,     0.58859,     0.58959,     0.59059,     0.59159,     0.59259,     0.59359,     0.59459,      0.5956,      0.5966,      0.5976,      0.5986,      0.5996,
            0.6006,      0.6016,      0.6026,      0.6036,      0.6046,     0.60561,     0.60661,     0.60761,     0.60861,     0.60961,     0.61061,     0.61161,     0.61261,     0.61361,     0.61461,     0.61562,     0.61662,     0.61762,     0.61862,     0.61962,     0.62062,     0.62162,     0.62262,     0.62362,
           0.62462,     0.62563,     0.62663,     0.62763,     0.62863,     0.62963,     0.63063,     0.63163,     0.63263,     0.63363,     0.63463,     0.63564,     0.63664,     0.63764,     0.63864,     0.63964,     0.64064,     0.64164,     0.64264,     0.64364,     0.64464,     0.64565,     0.64665,     0.64765,
           0.64865,     0.64965,     0.65065,     0.65165,     0.65265,     0.65365,     0.65465,     0.65566,     0.65666,     0.65766,     0.65866,     0.65966,     0.66066,     0.66166,     0.66266,     0.66366,     0.66466,     0.66567,     0.66667,     0.66767,     0.66867,     0.66967,     0.67067,     0.67167,
           0.67267,     0.67367,     0.67467,     0.67568,     0.67668,     0.67768,     0.67868,     0.67968,     0.68068,     0.68168,     0.68268,     0.68368,     0.68468,     0.68569,     0.68669,     0.68769,     0.68869,     0.68969,     0.69069,     0.69169,     0.69269,     0.69369,     0.69469,      0.6957,
            0.6967,      0.6977,      0.6987,      0.6997,      0.7007,      0.7017,      0.7027,      0.7037,      0.7047,     0.70571,     0.70671,     0.70771,     0.70871,     0.70971,     0.71071,     0.71171,     0.71271,     0.71371,     0.71471,     0.71572,     0.71672,     0.71772,     0.71872,     0.71972,
           0.72072,     0.72172,     0.72272,     0.72372,     0.72472,     0.72573,     0.72673,     0.72773,     0.72873,     0.72973,     0.73073,     0.73173,     0.73273,     0.73373,     0.73473,     0.73574,     0.73674,     0.73774,     0.73874,     0.73974,     0.74074,     0.74174,     0.74274,     0.74374,
           0.74474,     0.74575,     0.74675,     0.74775,     0.74875,     0.74975,     0.75075,     0.75175,     0.75275,     0.75375,     0.75475,     0.75576,     0.75676,     0.75776,     0.75876,     0.75976,     0.76076,     0.76176,     0.76276,     0.76376,     0.76476,     0.76577,     0.76677,     0.76777,
           0.76877,     0.76977,     0.77077,     0.77177,     0.77277,     0.77377,     0.77477,     0.77578,     0.77678,     0.77778,     0.77878,     0.77978,     0.78078,     0.78178,     0.78278,     0.78378,     0.78478,     0.78579,     0.78679,     0.78779,     0.78879,     0.78979,     0.79079,     0.79179,
           0.79279,     0.79379,     0.79479,      0.7958,      0.7968,      0.7978,      0.7988,      0.7998,      0.8008,      0.8018,      0.8028,      0.8038,      0.8048,     0.80581,     0.80681,     0.80781,     0.80881,     0.80981,     0.81081,     0.81181,     0.81281,     0.81381,     0.81481,     0.81582,
           0.81682,     0.81782,     0.81882,     0.81982,     0.82082,     0.82182,     0.82282,     0.82382,     0.82482,     0.82583,     0.82683,     0.82783,     0.82883,     0.82983,     0.83083,     0.83183,     0.83283,     0.83383,     0.83483,     0.83584,     0.83684,     0.83784,     0.83884,     0.83984,
           0.84084,     0.84184,     0.84284,     0.84384,     0.84484,     0.84585,     0.84685,     0.84785,     0.84885,     0.84985,     0.85085,     0.85185,     0.85285,     0.85385,     0.85485,     0.85586,     0.85686,     0.85786,     0.85886,     0.85986,     0.86086,     0.86186,     0.86286,     0.86386,
           0.86486,     0.86587,     0.86687,     0.86787,     0.86887,     0.86987,     0.87087,     0.87187,     0.87287,     0.87387,     0.87487,     0.87588,     0.87688,     0.87788,     0.87888,     0.87988,     0.88088,     0.88188,     0.88288,     0.88388,     0.88488,     0.88589,     0.88689,     0.88789,
           0.88889,     0.88989,     0.89089,     0.89189,     0.89289,     0.89389,     0.89489,      0.8959,      0.8969,      0.8979,      0.8989,      0.8999,      0.9009,      0.9019,      0.9029,      0.9039,      0.9049,     0.90591,     0.90691,     0.90791,     0.90891,     0.90991,     0.91091,     0.91191,
           0.91291,     0.91391,     0.91491,     0.91592,     0.91692,     0.91792,     0.91892,     0.91992,     0.92092,     0.92192,     0.92292,     0.92392,     0.92492,     0.92593,     0.92693,     0.92793,     0.92893,     0.92993,     0.93093,     0.93193,     0.93293,     0.93393,     0.93493,     0.93594,
           0.93694,     0.93794,     0.93894,     0.93994,     0.94094,     0.94194,     0.94294,     0.94394,     0.94494,     0.94595,     0.94695,     0.94795,     0.94895,     0.94995,     0.95095,     0.95195,     0.95295,     0.95395,     0.95495,     0.95596,     0.95696,     0.95796,     0.95896,     0.95996,
           0.96096,     0.96196,     0.96296,     0.96396,     0.96496,     0.96597,     0.96697,     0.96797,     0.96897,     0.96997,     0.97097,     0.97197,     0.97297,     0.97397,     0.97497,     0.97598,     0.97698,     0.97798,     0.97898,     0.97998,     0.98098,     0.98198,     0.98298,     0.98398,
           0.98498,     0.98599,     0.98699,     0.98799,     0.98899,     0.98999,     0.99099,     0.99199,     0.99299,     0.99399,     0.99499,       0.996,       0.997,       0.998,       0.999,           1]), array([[          1,           1,           1, ...,           0,           0,           0],
       [          1,           1,           1, ...,     0.28571,     0.28571,           0],
       [    0.11111,     0.11111,     0.11111, ...,           0,           0,           0],
       ...,
       [          1,           1,           1, ...,           0,           0,           0],
       [          1,           1,           1, ...,     0.20879,     0.20879,           0],
       [          1,           1,           1, ...,     0.38806,     0.38806,           0]], shape=(29, 1000)), 'Recall', 'Precision'], [array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,
           0.33634,     0.33734,     0.33834,     0.33934,     0.34034,     0.34134,     0.34234,     0.34334,     0.34434,     0.34535,     0.34635,     0.34735,     0.34835,     0.34935,     0.35035,     0.35135,     0.35235,     0.35335,     0.35435,     0.35536,     0.35636,     0.35736,     0.35836,     0.35936,
           0.36036,     0.36136,     0.36236,     0.36336,     0.36436,     0.36537,     0.36637,     0.36737,     0.36837,     0.36937,     0.37037,     0.37137,     0.37237,     0.37337,     0.37437,     0.37538,     0.37638,     0.37738,     0.37838,     0.37938,     0.38038,     0.38138,     0.38238,     0.38338,
           0.38438,     0.38539,     0.38639,     0.38739,     0.38839,     0.38939,     0.39039,     0.39139,     0.39239,     0.39339,     0.39439,      0.3954,      0.3964,      0.3974,      0.3984,      0.3994,      0.4004,      0.4014,      0.4024,      0.4034,      0.4044,     0.40541,     0.40641,     0.40741,

In [22]:
from ultralytics import YOLO

disease_best = "/kaggle/working/runs/dentex_disease_v1-3/weights/best.pt"

model_disease = YOLO(disease_best)

disease_metrics = model_disease.val(
    data="/kaggle/working/disease.yaml",
    imgsz=1024,
    batch=4
)

print(disease_metrics)

Ultralytics 8.4.83 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
Model summary (fused): 73 layers, 11,127,132 parameters, 0 gradients, 28.4 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 3749.6±1676.1 MB/s, size: 4718.1 KB)
val: Scanning /kaggle/working/dentex_disease_yolo/labels/val.cache... 71 images, 4 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 71/71 17.5Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 5.2it/s 3.5s0.2s
                   all         71        363      0.728      0.555      0.605      0.433
              Impacted         25         64      0.832      0.931      0.923       0.62
                Caries         61        246      0.512      0.418      0.486      0.352
     Periapical_Lesion         11         14      0.767      0.357      0.403      0.329
           Deep_Caries         25         39      0.801      0.513      0.609       0.43
Speed: 2.2ms preprocess, 14.5ms inference, 0.0ms loss, 3.2ms postprocess per image
Results saved to /kaggle/working/runs/detect/val-3
ultralytics.utils.metrics.DetMetrics object with attributes:

ap_class_index: array([0, 1, 2, 3])
box: ultralytics.utils.metrics.Metric object
confusion_matrix: <ultralytics.utils.metrics.ConfusionMatrix object at 0x7f5f581e01a0>
curves: ['Precision-Recall(B)', 'F1-Confidence(B)', 'Precision-Confidence(B)', 'Recall-Confidence(B)']
curves_results: [[array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,
           0.33634,     0.33734,     0.33834,     0.33934,     0.34034,     0.34134,     0.34234,     0.34334,     0.34434,     0.34535,     0.34635,     0.34735,     0.34835,     0.34935,     0.35035,     0.35135,     0.35235,     0.35335,     0.35435,     0.35536,     0.35636,     0.35736,     0.35836,     0.35936,
           0.36036,     0.36136,     0.36236,     0.36336,     0.36436,     0.36537,     0.36637,     0.36737,     0.36837,     0.36937,     0.37037,     0.37137,     0.37237,     0.37337,     0.37437,     0.37538,     0.37638,     0.37738,     0.37838,     0.37938,     0.38038,     0.38138,     0.38238,     0.38338,
           0.38438,     0.38539,     0.38639,     0.38739,     0.38839,     0.38939,     0.39039,     0.39139,     0.39239,     0.39339,     0.39439,      0.3954,      0.3964,      0.3974,      0.3984,      0.3994,      0.4004,      0.4014,      0.4024,      0.4034,      0.4044,     0.40541,     0.40641,     0.40741,
           0.40841,     0.40941,     0.41041,     0.41141,     0.41241,     0.41341,     0.41441,     0.41542,     0.41642,     0.41742,     0.41842,     0.41942,     0.42042,     0.42142,     0.42242,     0.42342,     0.42442,     0.42543,     0.42643,     0.42743,     0.42843,     0.42943,     0.43043,     0.43143,
           0.43243,     0.43343,     0.43443,     0.43544,     0.43644,     0.43744,     0.43844,     0.43944,     0.44044,     0.44144,     0.44244,     0.44344,     0.44444,     0.44545,     0.44645,     0.44745,     0.44845,     0.44945,     0.45045,     0.45145,     0.45245,     0.45345,     0.45445,     0.45546,
           0.45646,     0.45746,     0.45846,     0.45946,     0.46046,     0.46146,     0.46246,     0.46346,     0.46446,     0.46547,     0.46647,     0.46747,     0.46847,     0.46947,     0.47047,     0.47147,     0.47247,     0.47347,     0.47447,     0.47548,     0.47648,     0.47748,     0.47848,     0.47948,
           0.48048,     0.48148,     0.48248,     0.48348,     0.48448,     0.48549,     0.48649,     0.48749,     0.48849,     0.48949,     0.49049,     0.49149,     0.49249,     0.49349,     0.49449,      0.4955,      0.4965,      0.4975,      0.4985,      0.4995,      0.5005,      0.5015,      0.5025,      0.5035,
            0.5045,     0.50551,     0.50651,     0.50751,     0.50851,     0.50951,     0.51051,     0.51151,     0.51251,     0.51351,     0.51451,     0.51552,     0.51652,     0.51752,     0.51852,     0.51952,     0.52052,     0.52152,     0.52252,     0.52352,     0.52452,     0.52553,     0.52653,     0.52753,
           0.52853,     0.52953,     0.53053,     0.53153,     0.53253,     0.53353,     0.53453,     0.53554,     0.53654,     0.53754,     0.53854,     0.53954,     0.54054,     0.54154,     0.54254,     0.54354,     0.54454,     0.54555,     0.54655,     0.54755,     0.54855,     0.54955,     0.55055,     0.55155,
           0.55255,     0.55355,     0.55455,     0.55556,     0.55656,     0.55756,     0.55856,     0.55956,     0.56056,     0.56156,     0.56256,     0.56356,     0.56456,     0.56557,     0.56657,     0.56757,     0.56857,     0.56957,     0.57057,     0.57157,     0.57257,     0.57357,     0.57457,     0.57558,
           0.57658,     0.57758,     0.57858,     0.57958,     0.58058,     0.58158,     0.58258,     0.58358,     0.58458,     0.58559,     0.58659,     0.58759,     0.58859,     0.58959,     0.59059,     0.59159,     0.59259,     0.59359,     0.59459,      0.5956,      0.5966,      0.5976,      0.5986,      0.5996,
            0.6006,      0.6016,      0.6026,      0.6036,      0.6046,     0.60561,     0.60661,     0.60761,     0.60861,     0.60961,     0.61061,     0.61161,     0.61261,     0.61361,     0.61461,     0.61562,     0.61662,     0.61762,     0.61862,     0.61962,     0.62062,     0.62162,     0.62262,     0.62362,
           0.62462,     0.62563,     0.62663,     0.62763,     0.62863,     0.62963,     0.63063,     0.63163,     0.63263,     0.63363,     0.63463,     0.63564,     0.63664,     0.63764,     0.63864,     0.63964,     0.64064,     0.64164,     0.64264,     0.64364,     0.64464,     0.64565,     0.64665,     0.64765,
           0.64865,     0.64965,     0.65065,     0.65165,     0.65265,     0.65365,     0.65465,     0.65566,     0.65666,     0.65766,     0.65866,     0.65966,     0.66066,     0.66166,     0.66266,     0.66366,     0.66466,     0.66567,     0.66667,     0.66767,     0.66867,     0.66967,     0.67067,     0.67167,
           0.67267,     0.67367,     0.67467,     0.67568,     0.67668,     0.67768,     0.67868,     0.67968,     0.68068,     0.68168,     0.68268,     0.68368,     0.68468,     0.68569,     0.68669,     0.68769,     0.68869,     0.68969,     0.69069,     0.69169,     0.69269,     0.69369,     0.69469,      0.6957,
            0.6967,      0.6977,      0.6987,      0.6997,      0.7007,      0.7017,      0.7027,      0.7037,      0.7047,     0.70571,     0.70671,     0.70771,     0.70871,     0.70971,     0.71071,     0.71171,     0.71271,     0.71371,     0.71471,     0.71572,     0.71672,     0.71772,     0.71872,     0.71972,
           0.72072,     0.72172,     0.72272,     0.72372,     0.72472,     0.72573,     0.72673,     0.72773,     0.72873,     0.72973,     0.73073,     0.73173,     0.73273,     0.73373,     0.73473,     0.73574,     0.73674,     0.73774,     0.73874,     0.73974,     0.74074,     0.74174,     0.74274,     0.74374,
           0.74474,     0.74575,     0.74675,     0.74775,     0.74875,     0.74975,     0.75075,     0.75175,     0.75275,     0.75375,     0.75475,     0.75576,     0.75676,     0.75776,     0.75876,     0.75976,     0.76076,     0.76176,     0.76276,     0.76376,     0.76476,     0.76577,     0.76677,     0.76777,
           0.76877,     0.76977,     0.77077,     0.77177,     0.77277,     0.77377,     0.77477,     0.77578,     0.77678,     0.77778,     0.77878,     0.77978,     0.78078,     0.78178,     0.78278,     0.78378,     0.78478,     0.78579,     0.78679,     0.78779,     0.78879,     0.78979,     0.79079,     0.79179,
           0.79279,     0.79379,     0.79479,      0.7958,      0.7968,      0.7978,      0.7988,      0.7998,      0.8008,      0.8018,      0.8028,      0.8038,      0.8048,     0.80581,     0.80681,     0.80781,     0.80881,     0.80981,     0.81081,     0.81181,     0.81281,     0.81381,     0.81481,     0.81582,
           0.81682,     0.81782,     0.81882,     0.81982,     0.82082,     0.82182,     0.82282,     0.82382,     0.82482,     0.82583,     0.82683,     0.82783,     0.82883,     0.82983,     0.83083,     0.83183,     0.83283,     0.83383,     0.83483,     0.83584,     0.83684,     0.83784,     0.83884,     0.83984,
           0.84084,     0.84184,     0.84284,     0.84384,     0.84484,     0.84585,     0.84685,     0.84785,     0.84885,     0.84985,     0.85085,     0.85185,     0.85285,     0.85385,     0.85485,     0.85586,     0.85686,     0.85786,     0.85886,     0.85986,     0.86086,     0.86186,     0.86286,     0.86386,
           0.86486,     0.86587,     0.86687,     0.86787,     0.86887,     0.86987,     0.87087,     0.87187,     0.87287,     0.87387,     0.87487,     0.87588,     0.87688,     0.87788,     0.87888,     0.87988,     0.88088,     0.88188,     0.88288,     0.88388,     0.88488,     0.88589,     0.88689,     0.88789,
           0.88889,     0.88989,     0.89089,     0.89189,     0.89289,     0.89389,     0.89489,      0.8959,      0.8969,      0.8979,      0.8989,      0.8999,      0.9009,      0.9019,      0.9029,      0.9039,      0.9049,     0.90591,     0.90691,     0.90791,     0.90891,     0.90991,     0.91091,     0.91191,
           0.91291,     0.91391,     0.91491,     0.91592,     0.91692,     0.91792,     0.91892,     0.91992,     0.92092,     0.92192,     0.92292,     0.92392,     0.92492,     0.92593,     0.92693,     0.92793,     0.92893,     0.92993,     0.93093,     0.93193,     0.93293,     0.93393,     0.93493,     0.93594,
           0.93694,     0.93794,     0.93894,     0.93994,     0.94094,     0.94194,     0.94294,     0.94394,     0.94494,     0.94595,     0.94695,     0.94795,     0.94895,     0.94995,     0.95095,     0.95195,     0.95295,     0.95395,     0.95495,     0.95596,     0.95696,     0.95796,     0.95896,     0.95996,
           0.96096,     0.96196,     0.96296,     0.96396,     0.96496,     0.96597,     0.96697,     0.96797,     0.96897,     0.96997,     0.97097,     0.97197,     0.97297,     0.97397,     0.97497,     0.97598,     0.97698,     0.97798,     0.97898,     0.97998,     0.98098,     0.98198,     0.98298,     0.98398,
           0.98498,     0.98599,     0.98699,     0.98799,     0.98899,     0.98999,     0.99099,     0.99199,     0.99299,     0.99399,     0.99499,       0.996,       0.997,       0.998,       0.999,           1]), array([[          1,           1,           1, ...,           0,           0,           0],
       [          1,           1,           1, ...,           0,           0,           0],
       [          1,           1,           1, ...,           0,           0,           0],
       [          1,           1,           1, ...,           0,           0,           0]], shape=(4, 1000)), 'Recall', 'Precision'], [array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,
           0.33634,     0.33734,     0.33834,     0.33934,     0.34034,     0.34134,     0.34234,     0.34334,     0.34434,     0.34535,     0.34635,     0.34735,     0.34835,     0.34935,     0.35035,     0.35135,     0.35235,     0.35335,     0.35435,     0.35536,     0.35636,     0.35736,     0.35836,     0.35936,

In [ ]:
model_fdi.predict(
    source=f"{FDI_OUT}/images/val",
    imgsz=1024,
    conf=0.25,
    save=True,
    project=f"{WORK}/predictions",
    name="fdi_predictions"
)

In [16]:
model_disease = YOLO("yolov8s.pt")

model_disease.train(
    data=f"{WORK}/disease.yaml",
    epochs=100,
    imgsz=1024,
    batch=4,
    project=f"{WORK}/runs",
    name="dentex_disease_v1",
    patience=25,
    workers=2
)

Ultralytics 8.4.83 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=4, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/working/disease.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dis=6.0, distill_model=None, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=100, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=1024, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8s.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=dentex_disease_v1-3, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=25, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/kaggle/working/runs, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/kaggle/working/runs/dentex_disease_v1-3, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=2, workspace=None
Overriding model.yaml nc=80 with nc=4

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     29056  ultralytics.nn.modules.block.C2f             [64, 64, 1, True]
  3                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  4                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  5                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  6                  -1  2    788480  ultralytics.nn.modules.block.C2f             [256, 256, 2, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1838080  ultralytics.nn.modules.block.C2f             [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    591360  ultralytics.nn.modules.block.C2f             [768, 256, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 16                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 19                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1   1969152  ultralytics.nn.modules.block.C2f             [768, 512, 1]
 22        [15, 18, 21]  1   2117596  ultralytics.nn.modules.head.Detect           [4, 16, None, [128, 256, 512]]
Model summary: 130 layers, 11,137,148 parameters, 11,137,132 gradients, 28.7 GFLOPs

Transferred 349/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 5272.0±1009.3 MB/s, size: 3745.0 KB)
train: Scanning /kaggle/working/dentex_disease_yolo/labels/train.cache... 634 images, 23 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 634/634 265.9Mit/s 0.0s
train: /kaggle/working/dentex_disease_yolo/images/train/train_377.png: 1 duplicate labels removed
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 2394.4±2268.8 MB/s, size: 3733.4 KB)
val: Scanning /kaggle/working/dentex_disease_yolo/labels/val.cache... 71 images, 4 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 71/71 2.8Mit/s 0.0s
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.00125, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Plotting labels to /kaggle/working/runs/dentex_disease_v1-3/labels.jpg...
Image sizes 1024 train, 1024 val
Using 2 dataloader workers
Logging results to /kaggle/working/runs/dentex_disease_v1-3
Starting training for 100 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      1/100       3.4G      1.434      2.702      1.391         10       1024: 100% ━━━━━━━━━━━━ 159/159 4.0it/s 39.8s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 8.4it/s 1.1s0.1s
                   all         71        363      0.441       0.37      0.292      0.176

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      2/100      3.74G       1.21      1.939      1.212         11       1024: 100% ━━━━━━━━━━━━ 159/159 4.3it/s 37.0s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 7.5it/s 1.2s0.3s
                   all         71        363      0.631      0.399      0.327      0.214

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      3/100      3.74G      1.226      1.841      1.219         20       1024: 100% ━━━━━━━━━━━━ 159/159 4.2it/s 37.7s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 9.2it/s 1.0s0.2s
                   all         71        363      0.531      0.444      0.382      0.241

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      4/100      3.74G      1.189      1.787      1.216         14       1024: 100% ━━━━━━━━━━━━ 159/159 4.3it/s 37.0s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 7.7it/s 1.2s0.1s
                   all         71        363       0.56      0.489      0.396      0.253

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      5/100      3.74G      1.172      1.728      1.227         12       1024: 100% ━━━━━━━━━━━━ 159/159 4.3it/s 37.0s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 7.5it/s 1.2s0.1s
                   all         71        363       0.35      0.474      0.421      0.283

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      6/100      3.74G      1.127        1.7      1.184         21       1024: 100% ━━━━━━━━━━━━ 159/159 4.3it/s 37.0s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 7.7it/s 1.2s0.1s
                   all         71        363      0.624      0.483      0.413       0.27

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      7/100      3.74G      1.141      1.675      1.188         14       1024: 100% ━━━━━━━━━━━━ 159/159 4.3it/s 36.9s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 7.1it/s 1.3s0.1s
                   all         71        363      0.585      0.477      0.442      0.288

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      8/100      3.74G      1.112      1.573      1.176         13       1024: 100% ━━━━━━━━━━━━ 159/159 4.3it/s 36.7s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 7.5it/s 1.2s0.1s
                   all         71        363      0.619      0.488      0.456      0.313

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      9/100      3.74G      1.097      1.535      1.168         15       1024: 100% ━━━━━━━━━━━━ 159/159 4.3it/s 37.3s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 8.8it/s 1.0s0.3s
                   all         71        363      0.631      0.538      0.496      0.337

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     10/100      3.74G      1.121      1.523      1.177         42       1024: 100% ━━━━━━━━━━━━ 159/159 4.3it/s 37.3s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 7.9it/s 1.1s0.3s
                   all         71        363      0.423      0.571      0.472      0.307

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     11/100      3.74G      1.108      1.528      1.172         14       1024: 100% ━━━━━━━━━━━━ 159/159 4.3it/s 37.3s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 7.7it/s 1.2s0.1s
                   all         71        363      0.453      0.623       0.47      0.311

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     12/100      3.74G      1.075      1.455      1.155         12       1024: 100% ━━━━━━━━━━━━ 159/159 4.2it/s 37.4s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 7.7it/s 1.2s0.2s
                   all         71        363      0.442      0.609      0.524      0.343

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     13/100      3.74G      1.076      1.442      1.164          9       1024: 100% ━━━━━━━━━━━━ 159/159 4.2it/s 38.1s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 9.1it/s 1.0s0.3s
                   all         71        363      0.489      0.596      0.515      0.344

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     14/100      3.74G      1.082       1.42      1.158         23       1024: 100% ━━━━━━━━━━━━ 159/159 4.2it/s 37.5s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 7.2it/s 1.3s0.1s
                   all         71        363      0.417       0.51      0.483      0.335

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     15/100      3.74G      1.066      1.407       1.15         25       1024: 100% ━━━━━━━━━━━━ 159/159 4.3it/s 37.1s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 8.0it/s 1.1s0.1s
                   all         71        363      0.608      0.477      0.504      0.344

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     16/100      3.74G      1.041      1.374      1.138          7       1024: 100% ━━━━━━━━━━━━ 159/159 4.2it/s 37.5s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 7.9it/s 1.1s0.3s
                   all         71        363      0.491      0.541      0.474       0.33

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     17/100      3.74G      1.038      1.361      1.129         15       1024: 100% ━━━━━━━━━━━━ 159/159 4.3it/s 36.8s0.4ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 7.9it/s 1.1s0.1s
                   all         71        363      0.553      0.532      0.536      0.372

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     18/100      3.74G      1.041      1.364      1.129          9       1024: 100% ━━━━━━━━━━━━ 159/159 4.2it/s 37.8s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 7.9it/s 1.1s0.1s
                   all         71        363      0.674      0.548      0.591      0.406

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     19/100      3.74G      1.017      1.343      1.116         24       1024: 100% ━━━━━━━━━━━━ 159/159 4.2it/s 38.1s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 9.2it/s 1.0s0.1s
                   all         71        363      0.523      0.552      0.529      0.366

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     20/100      3.74G      1.028      1.315      1.128         25       1024: 100% ━━━━━━━━━━━━ 159/159 4.2it/s 38.0s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 8.0it/s 1.1s0.1s
                   all         71        363      0.617       0.56      0.563      0.374

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     21/100      3.74G      1.054      1.335      1.134         14       1024: 100% ━━━━━━━━━━━━ 159/159 4.1it/s 38.5s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 7.5it/s 1.2s0.1s
                   all         71        363      0.445      0.573      0.495       0.34

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     22/100      3.74G      1.027      1.327      1.124         21       1024: 100% ━━━━━━━━━━━━ 159/159 4.2it/s 38.2s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 7.7it/s 1.2s0.1s
                   all         71        363      0.631      0.536      0.513      0.357

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     23/100      3.74G      1.009       1.27      1.113         15       1024: 100% ━━━━━━━━━━━━ 159/159 4.1it/s 39.1s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 7.7it/s 1.2s0.1s
                   all         71        363      0.515      0.589      0.555      0.386

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     24/100      3.74G      0.992      1.273      1.102         28       1024: 100% ━━━━━━━━━━━━ 159/159 4.1it/s 38.9s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 7.0it/s 1.3s0.1s
                   all         71        363      0.575      0.628      0.591      0.406

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     25/100      3.74G     0.9956      1.242      1.099         21       1024: 100% ━━━━━━━━━━━━ 159/159 4.1it/s 38.9s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 6.9it/s 1.3s0.1s
                   all         71        363      0.597      0.551      0.589      0.404

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     26/100      3.74G     0.9957      1.256      1.102         15       1024: 100% ━━━━━━━━━━━━ 159/159 4.1it/s 39.0s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 6.7it/s 1.3s0.1s
                   all         71        363      0.503      0.584      0.536       0.36

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     27/100      3.74G     0.9891       1.24      1.102         14       1024: 100% ━━━━━━━━━━━━ 159/159 4.1it/s 38.7s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 6.7it/s 1.3s0.1s
                   all         71        363      0.534      0.579      0.533      0.356

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     28/100      3.74G     0.9803      1.218      1.093         21       1024: 100% ━━━━━━━━━━━━ 159/159 4.1it/s 38.4s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 8.1it/s 1.1s0.1s
                   all         71        363      0.641      0.557      0.569      0.402

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     29/100      3.74G     0.9811      1.217      1.087         26       1024: 100% ━━━━━━━━━━━━ 159/159 4.1it/s 38.7s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 7.0it/s 1.3s0.1s
                   all         71        363      0.675       0.56      0.594      0.413

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     30/100      3.74G     0.9763        1.2      1.087         35       1024: 100% ━━━━━━━━━━━━ 159/159 4.1it/s 38.7s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 8.6it/s 1.1s0.1s
                   all         71        363      0.595       0.56      0.572      0.397

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     31/100      3.74G     0.9708      1.171      1.091         26       1024: 100% ━━━━━━━━━━━━ 159/159 4.2it/s 38.1s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 7.5it/s 1.2s0.1s
                   all         71        363      0.626      0.553      0.577      0.408

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     32/100      3.74G     0.9619      1.176      1.089          8       1024: 100% ━━━━━━━━━━━━ 159/159 4.1it/s 38.7s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 7.1it/s 1.3s0.3s
                   all         71        363      0.647      0.562      0.594      0.422

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     33/100      3.74G     0.9252      1.135      1.063         10       1024: 100% ━━━━━━━━━━━━ 159/159 4.1it/s 38.7s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 8.0it/s 1.1s0.1s
                   all         71        363      0.596      0.577      0.571      0.391

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     34/100      3.74G     0.9422      1.118      1.076         36       1024: 100% ━━━━━━━━━━━━ 159/159 4.2it/s 38.3s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 9/9 7.9it/s 1.1s0.1s

ultralytics.utils.metrics.DetMetrics object with attributes:

ap_class_index: array([0, 1, 2, 3])
box: ultralytics.utils.metrics.Metric object
confusion_matrix: <ultralytics.utils.metrics.ConfusionMatrix object at 0x7f5f4fc1f4d0>
curves: ['Precision-Recall(B)', 'F1-Confidence(B)', 'Precision-Confidence(B)', 'Recall-Confidence(B)']
curves_results: [[array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,
           0.33634,     0.33734,     0.33834,     0.33934,     0.34034,     0.34134,     0.34234,     0.34334,     0.34434,     0.34535,     0.34635,     0.34735,     0.34835,     0.34935,     0.35035,     0.35135,     0.35235,     0.35335,     0.35435,     0.35536,     0.35636,     0.35736,     0.35836,     0.35936,
           0.36036,     0.36136,     0.36236,     0.36336,     0.36436,     0.36537,     0.36637,     0.36737,     0.36837,     0.36937,     0.37037,     0.37137,     0.37237,     0.37337,     0.37437,     0.37538,     0.37638,     0.37738,     0.37838,     0.37938,     0.38038,     0.38138,     0.38238,     0.38338,
           0.38438,     0.38539,     0.38639,     0.38739,     0.38839,     0.38939,     0.39039,     0.39139,     0.39239,     0.39339,     0.39439,      0.3954,      0.3964,      0.3974,      0.3984,      0.3994,      0.4004,      0.4014,      0.4024,      0.4034,      0.4044,     0.40541,     0.40641,     0.40741,
           0.40841,     0.40941,     0.41041,     0.41141,     0.41241,     0.41341,     0.41441,     0.41542,     0.41642,     0.41742,     0.41842,     0.41942,     0.42042,     0.42142,     0.42242,     0.42342,     0.42442,     0.42543,     0.42643,     0.42743,     0.42843,     0.42943,     0.43043,     0.43143,
           0.43243,     0.43343,     0.43443,     0.43544,     0.43644,     0.43744,     0.43844,     0.43944,     0.44044,     0.44144,     0.44244,     0.44344,     0.44444,     0.44545,     0.44645,     0.44745,     0.44845,     0.44945,     0.45045,     0.45145,     0.45245,     0.45345,     0.45445,     0.45546,
           0.45646,     0.45746,     0.45846,     0.45946,     0.46046,     0.46146,     0.46246,     0.46346,     0.46446,     0.46547,     0.46647,     0.46747,     0.46847,     0.46947,     0.47047,     0.47147,     0.47247,     0.47347,     0.47447,     0.47548,     0.47648,     0.47748,     0.47848,     0.47948,
           0.48048,     0.48148,     0.48248,     0.48348,     0.48448,     0.48549,     0.48649,     0.48749,     0.48849,     0.48949,     0.49049,     0.49149,     0.49249,     0.49349,     0.49449,      0.4955,      0.4965,      0.4975,      0.4985,      0.4995,      0.5005,      0.5015,      0.5025,      0.5035,
            0.5045,     0.50551,     0.50651,     0.50751,     0.50851,     0.50951,     0.51051,     0.51151,     0.51251,     0.51351,     0.51451,     0.51552,     0.51652,     0.51752,     0.51852,     0.51952,     0.52052,     0.52152,     0.52252,     0.52352,     0.52452,     0.52553,     0.52653,     0.52753,
           0.52853,     0.52953,     0.53053,     0.53153,     0.53253,     0.53353,     0.53453,     0.53554,     0.53654,     0.53754,     0.53854,     0.53954,     0.54054,     0.54154,     0.54254,     0.54354,     0.54454,     0.54555,     0.54655,     0.54755,     0.54855,     0.54955,     0.55055,     0.55155,
           0.55255,     0.55355,     0.55455,     0.55556,     0.55656,     0.55756,     0.55856,     0.55956,     0.56056,     0.56156,     0.56256,     0.56356,     0.56456,     0.56557,     0.56657,     0.56757,     0.56857,     0.56957,     0.57057,     0.57157,     0.57257,     0.57357,     0.57457,     0.57558,
           0.57658,     0.57758,     0.57858,     0.57958,     0.58058,     0.58158,     0.58258,     0.58358,     0.58458,     0.58559,     0.58659,     0.58759,     0.58859,     0.58959,     0.59059,     0.59159,     0.59259,     0.59359,     0.59459,      0.5956,      0.5966,      0.5976,      0.5986,      0.5996,
            0.6006,      0.6016,      0.6026,      0.6036,      0.6046,     0.60561,     0.60661,     0.60761,     0.60861,     0.60961,     0.61061,     0.61161,     0.61261,     0.61361,     0.61461,     0.61562,     0.61662,     0.61762,     0.61862,     0.61962,     0.62062,     0.62162,     0.62262,     0.62362,
           0.62462,     0.62563,     0.62663,     0.62763,     0.62863,     0.62963,     0.63063,     0.63163,     0.63263,     0.63363,     0.63463,     0.63564,     0.63664,     0.63764,     0.63864,     0.63964,     0.64064,     0.64164,     0.64264,     0.64364,     0.64464,     0.64565,     0.64665,     0.64765,
           0.64865,     0.64965,     0.65065,     0.65165,     0.65265,     0.65365,     0.65465,     0.65566,     0.65666,     0.65766,     0.65866,     0.65966,     0.66066,     0.66166,     0.66266,     0.66366,     0.66466,     0.66567,     0.66667,     0.66767,     0.66867,     0.66967,     0.67067,     0.67167,
           0.67267,     0.67367,     0.67467,     0.67568,     0.67668,     0.67768,     0.67868,     0.67968,     0.68068,     0.68168,     0.68268,     0.68368,     0.68468,     0.68569,     0.68669,     0.68769,     0.68869,     0.68969,     0.69069,     0.69169,     0.69269,     0.69369,     0.69469,      0.6957,
            0.6967,      0.6977,      0.6987,      0.6997,      0.7007,      0.7017,      0.7027,      0.7037,      0.7047,     0.70571,     0.70671,     0.70771,     0.70871,     0.70971,     0.71071,     0.71171,     0.71271,     0.71371,     0.71471,     0.71572,     0.71672,     0.71772,     0.71872,     0.71972,
           0.72072,     0.72172,     0.72272,     0.72372,     0.72472,     0.72573,     0.72673,     0.72773,     0.72873,     0.72973,     0.73073,     0.73173,     0.73273,     0.73373,     0.73473,     0.73574,     0.73674,     0.73774,     0.73874,     0.73974,     0.74074,     0.74174,     0.74274,     0.74374,
           0.74474,     0.74575,     0.74675,     0.74775,     0.74875,     0.74975,     0.75075,     0.75175,     0.75275,     0.75375,     0.75475,     0.75576,     0.75676,     0.75776,     0.75876,     0.75976,     0.76076,     0.76176,     0.76276,     0.76376,     0.76476,     0.76577,     0.76677,     0.76777,
           0.76877,     0.76977,     0.77077,     0.77177,     0.77277,     0.77377,     0.77477,     0.77578,     0.77678,     0.77778,     0.77878,     0.77978,     0.78078,     0.78178,     0.78278,     0.78378,     0.78478,     0.78579,     0.78679,     0.78779,     0.78879,     0.78979,     0.79079,     0.79179,
           0.79279,     0.79379,     0.79479,      0.7958,      0.7968,      0.7978,      0.7988,      0.7998,      0.8008,      0.8018,      0.8028,      0.8038,      0.8048,     0.80581,     0.80681,     0.80781,     0.80881,     0.80981,     0.81081,     0.81181,     0.81281,     0.81381,     0.81481,     0.81582,
           0.81682,     0.81782,     0.81882,     0.81982,     0.82082,     0.82182,     0.82282,     0.82382,     0.82482,     0.82583,     0.82683,     0.82783,     0.82883,     0.82983,     0.83083,     0.83183,     0.83283,     0.83383,     0.83483,     0.83584,     0.83684,     0.83784,     0.83884,     0.83984,
           0.84084,     0.84184,     0.84284,     0.84384,     0.84484,     0.84585,     0.84685,     0.84785,     0.84885,     0.84985,     0.85085,     0.85185,     0.85285,     0.85385,     0.85485,     0.85586,     0.85686,     0.85786,     0.85886,     0.85986,     0.86086,     0.86186,     0.86286,     0.86386,
           0.86486,     0.86587,     0.86687,     0.86787,     0.86887,     0.86987,     0.87087,     0.87187,     0.87287,     0.87387,     0.87487,     0.87588,     0.87688,     0.87788,     0.87888,     0.87988,     0.88088,     0.88188,     0.88288,     0.88388,     0.88488,     0.88589,     0.88689,     0.88789,
           0.88889,     0.88989,     0.89089,     0.89189,     0.89289,     0.89389,     0.89489,      0.8959,      0.8969,      0.8979,      0.8989,      0.8999,      0.9009,      0.9019,      0.9029,      0.9039,      0.9049,     0.90591,     0.90691,     0.90791,     0.90891,     0.90991,     0.91091,     0.91191,
           0.91291,     0.91391,     0.91491,     0.91592,     0.91692,     0.91792,     0.91892,     0.91992,     0.92092,     0.92192,     0.92292,     0.92392,     0.92492,     0.92593,     0.92693,     0.92793,     0.92893,     0.92993,     0.93093,     0.93193,     0.93293,     0.93393,     0.93493,     0.93594,
           0.93694,     0.93794,     0.93894,     0.93994,     0.94094,     0.94194,     0.94294,     0.94394,     0.94494,     0.94595,     0.94695,     0.94795,     0.94895,     0.94995,     0.95095,     0.95195,     0.95295,     0.95395,     0.95495,     0.95596,     0.95696,     0.95796,     0.95896,     0.95996,
           0.96096,     0.96196,     0.96296,     0.96396,     0.96496,     0.96597,     0.96697,     0.96797,     0.96897,     0.96997,     0.97097,     0.97197,     0.97297,     0.97397,     0.97497,     0.97598,     0.97698,     0.97798,     0.97898,     0.97998,     0.98098,     0.98198,     0.98298,     0.98398,
           0.98498,     0.98599,     0.98699,     0.98799,     0.98899,     0.98999,     0.99099,     0.99199,     0.99299,     0.99399,     0.99499,       0.996,       0.997,       0.998,       0.999,           1]), array([[          1,           1,           1, ...,           0,           0,           0],
       [          1,           1,           1, ...,           0,           0,           0],
       [          1,           1,           1, ...,           0,           0,           0],
       [          1,           1,           1, ...,           0,           0,           0]], shape=(4, 1000)), 'Recall', 'Precision'], [array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,
           0.33634,     0.33734,     0.33834,     0.33934,     0.34034,     0.34134,     0.34234,     0.34334,     0.34434,     0.34535,     0.34635,     0.34735,     0.34835,     0.34935,     0.35035,     0.35135,     0.35235,     0.35335,     0.35435,     0.35536,     0.35636,     0.35736,     0.35836,     0.35936,
           0.36036,     0.36136,     0.36236,     0.36336,     0.36436,     0.36537,     0.36637,     0.36737,     0.36837,     0.36937,     0.37037,     0.37137,     0.37237,     0.37337,     0.37437,     0.37538,     0.37638,     0.37738,     0.37838,     0.37938,     0.38038,     0.38138,     0.38238,     0.38338,
           0.38438,     0.38539,     0.38639,     0.38739,     0.38839,     0.38939,     0.39039,     0.39139,     0.39239,     0.39339,     0.39439,      0.3954,      0.3964,      0.3974,      0.3984,      0.3994,      0.4004,      0.4014,      0.4024,      0.4034,      0.4044,     0.40541,     0.40641,     0.40741,
           0.40841,     0.40941,     0.41041,     0.41141,     0.41241,     0.41341,     0.41441,     0.41542,     0.41642,     0.41742,     0.41842,     0.41942,     0.42042,     0.42142,     0.42242,     0.42342,     0.42442,     0.42543,     0.42643,     0.42743,     0.42843,     0.42943,     0.43043,     0.43143,

In [25]:
from pathlib import Path
import os, time

runs_dir = Path("/kaggle/working/runs")

pt_files = list(runs_dir.glob("**/weights/*.pt"))

print("MODELLI .pt TROVATI:")
for p in sorted(pt_files, key=lambda x: x.stat().st_mtime):
    size_mb = p.stat().st_size / 1024 / 1024
    modified = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(p.stat().st_mtime))
    print(f"{p} | {size_mb:.2f} MB | modified: {modified}")

MODELLI .pt TROVATI:
/kaggle/working/runs/dentex_disease_v1/weights/last.pt | 85.40 MB | modified: 2026-06-30 07:54:38
/kaggle/working/runs/dentex_disease_v1/weights/best.pt | 0.00 MB | modified: 2026-06-30 07:54:38
/kaggle/working/runs/dentex_fdi_v1/weights/best.pt | 85.49 MB | modified: 2026-06-30 08:12:00
/kaggle/working/runs/dentex_fdi_v1/weights/last.pt | 85.49 MB | modified: 2026-06-30 08:15:22
/kaggle/working/runs/dentex_fdi_v1-2/weights/last.pt | 83.66 MB | modified: 2026-06-30 09:43:18
/kaggle/working/runs/dentex_fdi_v1-2/weights/best.pt | 83.66 MB | modified: 2026-06-30 09:43:19
/kaggle/working/runs/dentex_disease_v1-3/weights/last.pt | 21.51 MB | modified: 2026-06-30 11:06:29
/kaggle/working/runs/dentex_disease_v1-3/weights/best.pt | 21.51 MB | modified: 2026-06-30 11:06:30

In [26]:
from ultralytics import YOLO

FDI_BEST = "/kaggle/working/runs/dentex_fdi_v1-2/weights/best.pt"
DISEASE_BEST = "/kaggle/working/runs/dentex_disease_v1-3/weights/best.pt"

fdi_model = YOLO(FDI_BEST)
disease_model = YOLO(DISEASE_BEST)

print("VALIDAZIONE FDI")
fdi_metrics = fdi_model.val(
    data="/kaggle/working/fdi.yaml",
    imgsz=1024,
    batch=4,
    project="/kaggle/working/validation",
    name="fdi_val"
)

print("VALIDAZIONE DISEASE")
disease_metrics = disease_model.val(
    data="/kaggle/working/disease.yaml",
    imgsz=1024,
    batch=4,
    project="/kaggle/working/validation",
    name="disease_val"
)

VALIDAZIONE FDI
Ultralytics 8.4.83 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
Model summary (fused): 113 layers, 43,631,280 parameters, 0 gradients, 165.0 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 4643.6±657.9 MB/s, size: 4220.6 KB)
val: Scanning /kaggle/working/dentex_fdi_yolo/labels/val.cache... 71 images, 4 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 71/71 33.1Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 3.3it/s 5.5s0.3s
                   all         71        363      0.575      0.473      0.472      0.337
                    11          6          6      0.261      0.333      0.394       0.31
                    12          4          4      0.674      0.523      0.754      0.525
                    13          2          2          1          0      0.055      0.044
                    14         10         10      0.652        0.4      0.405      0.316
                    15         14         14      0.606      0.714       0.73      0.506
                    16         19         19      0.396      0.691      0.573      0.442
                    17         11         11      0.247      0.455      0.321      0.236
                    18         20         20      0.628      0.676      0.667      0.433
                    21          6          6      0.659      0.326      0.313      0.278
                    22          3          3      0.132      0.333      0.067     0.0603
                    23          3          3      0.455      0.667      0.607       0.37
                    24          8          8       0.75      0.375      0.475       0.34
                    25         10         10      0.431        0.5      0.518      0.332
                    26         17         17      0.425      0.765      0.602      0.443
                    27         12         12      0.458      0.636       0.59      0.426
                    28         20         20      0.661       0.75      0.668      0.378
                    33          2          2          1          0     0.0825     0.0743
                    34         11         11      0.382      0.455      0.455      0.302
                    35         16         17      0.701      0.588      0.584       0.43
                    36         23         24      0.639      0.665      0.671      0.512
                    37         20         22      0.381      0.364      0.486       0.36
                    38         30         30      0.805      0.827      0.894      0.626
                    42          2          2          0          0          0          0
                    43          2          2          1          0      0.143        0.1
                    44          5          5          1          0     0.0519     0.0416
                    45         10         10      0.569       0.53      0.437      0.307
                    46         26         28      0.673      0.736      0.743      0.612
                    47         19         19      0.385      0.526      0.507      0.404
                    48         26         26      0.698      0.885      0.881      0.561
Speed: 3.8ms preprocess, 64.1ms inference, 0.0ms loss, 1.1ms postprocess per image
Results saved to /kaggle/working/validation/fdi_val
VALIDAZIONE DISEASE
Ultralytics 8.4.83 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
Model summary (fused): 73 layers, 11,127,132 parameters, 0 gradients, 28.4 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 3968.3±1323.1 MB/s, size: 4143.6 KB)
val: Scanning /kaggle/working/dentex_disease_yolo/labels/val.cache... 71 images, 4 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 71/71 5.2Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 5.3it/s 3.4s0.2s
                   all         71        363      0.728      0.555      0.605      0.433
              Impacted         25         64      0.832      0.931      0.923       0.62
                Caries         61        246      0.512      0.418      0.486      0.352
     Periapical_Lesion         11         14      0.767      0.357      0.403      0.329
           Deep_Caries         25         39      0.801      0.513      0.609       0.43
Speed: 2.6ms preprocess, 13.9ms inference, 0.0ms loss, 1.6ms postprocess per image
Results saved to /kaggle/working/validation/disease_val

In [27]:
from ultralytics import YOLO
from pathlib import Path

FDI_BEST = "/kaggle/working/runs/dentex_fdi_v1-2/weights/best.pt"
DISEASE_BEST = "/kaggle/working/runs/dentex_disease_v1-3/weights/best.pt"

FDI_VAL_IMAGES = "/kaggle/working/dentex_fdi_yolo/images/val"
DISEASE_VAL_IMAGES = "/kaggle/working/dentex_disease_yolo/images/val"

fdi_model = YOLO(FDI_BEST)
disease_model = YOLO(DISEASE_BEST)

# Prendiamo 10 immagini di validation
sample_images = sorted(list(Path(FDI_VAL_IMAGES).glob("*")))[:10]

print("Immagini usate:")
for img in sample_images:
    print(img)

fdi_model.predict(
    source=[str(p) for p in sample_images],
    imgsz=1024,
    conf=0.25,
    save=True,
    project="/kaggle/working/predictions",
    name="fdi_sample"
)

disease_model.predict(
    source=[str(p) for p in sample_images],
    imgsz=1024,
    conf=0.25,
    save=True,
    project="/kaggle/working/predictions",
    name="disease_sample"
)

Immagini usate:
/kaggle/working/dentex_fdi_yolo/images/val/train_127.png
/kaggle/working/dentex_fdi_yolo/images/val/train_148.png
/kaggle/working/dentex_fdi_yolo/images/val/train_171.png
/kaggle/working/dentex_fdi_yolo/images/val/train_172.png
/kaggle/working/dentex_fdi_yolo/images/val/train_177.png
/kaggle/working/dentex_fdi_yolo/images/val/train_182.png
/kaggle/working/dentex_fdi_yolo/images/val/train_201.png
/kaggle/working/dentex_fdi_yolo/images/val/train_220.png
/kaggle/working/dentex_fdi_yolo/images/val/train_224.png
/kaggle/working/dentex_fdi_yolo/images/val/train_235.png

0: 1024x1024 1 25, 1 26, 1 48, 108.8ms
1: 1024x1024 1 18, 1 24, 1 25, 1 26, 1 28, 1 35, 1 36, 1 38, 1 45, 1 46, 1 47, 1 48, 108.8ms
2: 1024x1024 1 16, 1 17, 1 18, 1 26, 1 27, 1 34, 1 35, 1 46, 1 47, 108.8ms
3: 1024x1024 1 26, 1 38, 1 46, 2 47s, 108.8ms
4: 1024x1024 1 34, 1 36, 108.8ms
5: 1024x1024 1 15, 1 18, 1 27, 1 37, 1 46, 1 47, 108.8ms
6: 1024x1024 1 16, 1 17, 1 28, 1 37, 1 38, 1 46, 1 48, 108.8ms
7: 1024x1024 1 16, 1 18, 1 48, 108.8ms
8: 1024x1024 1 25, 1 26, 1 28, 1 35, 1 38, 1 45, 1 48, 108.8ms
9: 1024x1024 1 14, 1 15, 1 16, 1 26, 1 38, 1 47, 108.8ms
Speed: 5.9ms preprocess, 108.8ms inference, 0.8ms postprocess per image at shape (1, 3, 1024, 1024)
Results saved to /kaggle/working/predictions/fdi_sample

0: 1024x1024 2 Cariess, 23.6ms
1: 1024x1024 4 Impacteds, 12 Cariess, 3 Deep_Cariess, 23.6ms
2: 1024x1024 1 Impacted, 7 Cariess, 23.6ms
3: 1024x1024 1 Impacted, 6 Cariess, 1 Deep_Caries, 23.6ms
4: 1024x1024 1 Deep_Caries, 23.6ms
5: 1024x1024 2 Cariess, 23.6ms
6: 1024x1024 1 Impacted, 9 Cariess, 23.6ms
7: 1024x1024 3 Impacteds, 3 Cariess, 23.6ms
8: 1024x1024 3 Impacteds, 3 Cariess, 1 Deep_Caries, 23.6ms
9: 1024x1024 5 Cariess, 23.6ms
Speed: 5.6ms preprocess, 23.6ms inference, 0.8ms postprocess per image at shape (1, 3, 1024, 1024)
Results saved to /kaggle/working/predictions/disease_sample

[ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'Impacted', 1: 'Caries', 2: 'Periapical_Lesion', 3: 'Deep_Caries'}
 obb: None
 orig_img: array([[[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        ...,

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]]], shape=(1316, 2842, 3), dtype=uint8)
 orig_shape: (1316, 2842)
 path: 'image0.jpg'
 probs: None
 save_dir: '/kaggle/working/predictions/disease_sample'
 semantic_mask: None
 speed: {'preprocess': 5.556212699957541, 'inference': 23.642169300001115, 'postprocess': 0.8009758999833139},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'Impacted', 1: 'Caries', 2: 'Periapical_Lesion', 3: 'Deep_Caries'}
 obb: None
 orig_img: array([[[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [244, 244, 244],
         [244, 244, 244],
         [244, 244, 244]],

        [[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [244, 244, 244],
         [244, 244, 244],
         [244, 244, 244]],

        [[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [244, 244, 244],
         [244, 244, 244],
         [244, 244, 244]],

        ...,

        [[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [251, 251, 251],
         [252, 252, 252],
         [252, 252, 252]],

        [[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [206, 206, 206],
         [201, 201, 201],
         [212, 212, 212]],

        [[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [181, 181, 181],
         [174, 174, 174],
         [182, 182, 182]]], shape=(1504, 2872, 3), dtype=uint8)
 orig_shape: (1504, 2872)
 path: 'image1.jpg'
 probs: None
 save_dir: '/kaggle/working/predictions/disease_sample'
 semantic_mask: None
 speed: {'preprocess': 5.556212699957541, 'inference': 23.642169300001115, 'postprocess': 0.8009758999833139},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'Impacted', 1: 'Caries', 2: 'Periapical_Lesion', 3: 'Deep_Caries'}
 obb: None
 orig_img: array([[[252, 252, 252],
         [253, 253, 253],
         [253, 253, 253],
         ...,
         [251, 251, 251],
         [251, 251, 251],
         [251, 251, 251]],

        [[252, 252, 252],
         [252, 252, 252],
         [252, 252, 252],
         ...,
         [251, 251, 251],
         [251, 251, 251],
         [251, 251, 251]],

        [[253, 253, 253],
         [252, 252, 252],
         [252, 252, 252],
         ...,
         [251, 251, 251],
         [251, 251, 251],
         [251, 251, 251]],

        ...,

        [[250, 250, 250],
         [249, 249, 249],
         [248, 248, 248],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[250, 250, 250],
         [249, 249, 249],
         [248, 248, 248],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[250, 250, 250],
         [249, 249, 249],
         [248, 248, 248],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]]], shape=(1316, 2882, 3), dtype=uint8)
 orig_shape: (1316, 2882)
 path: 'image2.jpg'
 probs: None
 save_dir: '/kaggle/working/predictions/disease_sample'
 semantic_mask: None
 speed: {'preprocess': 5.556212699957541, 'inference': 23.642169300001115, 'postprocess': 0.8009758999833139},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'Impacted', 1: 'Caries', 2: 'Periapical_Lesion', 3: 'Deep_Caries'}
 obb: None
 orig_img: array([[[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        ...,

        [[255, 255, 255],
         [255, 255, 255],
         [254, 254, 254],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]]], shape=(1316, 2885, 3), dtype=uint8)
 orig_shape: (1316, 2885)
 path: 'image3.jpg'
 probs: None
 save_dir: '/kaggle/working/predictions/disease_sample'
 semantic_mask: None
 speed: {'preprocess': 5.556212699957541, 'inference': 23.642169300001115, 'postprocess': 0.8009758999833139},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'Impacted', 1: 'Caries', 2: 'Periapical_Lesion', 3: 'Deep_Caries'}
 obb: None
 orig_img: array([[[253, 253, 253],
         [253, 253, 253],
         [253, 253, 253],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[253, 253, 253],
         [253, 253, 253],
         [253, 253, 253],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [254, 254, 254],
         [254, 254, 254],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        ...,

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]]], shape=(1316, 2814, 3), dtype=uint8)
 orig_shape: (1316, 2814)
 path: 'image4.jpg'
 probs: None
 save_dir: '/kaggle/working/predictions/disease_sample'
 semantic_mask: None
 speed: {'preprocess': 5.556212699957541, 'inference': 23.642169300001115, 'postprocess': 0.8009758999833139},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'Impacted', 1: 'Caries', 2: 'Periapical_Lesion', 3: 'Deep_Caries'}
 obb: None
 orig_img: array([[[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        ...,

        [[255, 255, 255],
         [255, 255, 255],
         [254, 254, 254],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]]], shape=(1316, 3003, 3), dtype=uint8)
 orig_shape: (1316, 3003)
 path: 'image5.jpg'
 probs: None
 save_dir: '/kaggle/working/predictions/disease_sample'
 semantic_mask: None
 speed: {'preprocess': 5.556212699957541, 'inference': 23.642169300001115, 'postprocess': 0.8009758999833139},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'Impacted', 1: 'Caries', 2: 'Periapical_Lesion', 3: 'Deep_Caries'}
 obb: None
 orig_img: array([[[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [238, 238, 238],
         [237, 237, 237],
         [235, 235, 235]],

        [[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [236, 236, 236],
         [235, 235, 235],
         [235, 235, 235]],

        [[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [235, 235, 235],
         [234, 234, 234],
         [235, 235, 235]],

        ...,

        [[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [248, 248, 248],
         [248, 248, 248],
         [248, 248, 248]],

        [[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [216, 216, 216],
         [211, 211, 211],
         [217, 217, 217]],

        [[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [184, 184, 184],
         [175, 175, 175],
         [187, 187, 187]]], shape=(1504, 2868, 3), dtype=uint8)
 orig_shape: (1504, 2868)
 path: 'image6.jpg'
 probs: None
 save_dir: '/kaggle/working/predictions/disease_sample'
 semantic_mask: None
 speed: {'preprocess': 5.556212699957541, 'inference': 23.642169300001115, 'postprocess': 0.8009758999833139},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'Impacted', 1: 'Caries', 2: 'Periapical_Lesion', 3: 'Deep_Caries'}
 obb: None
 orig_img: array([[[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        ...,

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[253, 253, 253],
         [253, 253, 253],
         [253, 253, 253],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]]], shape=(1316, 2920, 3), dtype=uint8)
 orig_shape: (1316, 2920)
 path: 'image7.jpg'
 probs: None
 save_dir: '/kaggle/working/predictions/disease_sample'
 semantic_mask: None
 speed: {'preprocess': 5.556212699957541, 'inference': 23.642169300001115, 'postprocess': 0.8009758999833139},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'Impacted', 1: 'Caries', 2: 'Periapical_Lesion', 3: 'Deep_Caries'}
 obb: None
 orig_img: array([[[254, 254, 254],
         [254, 254, 254],
         [254, 254, 254],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[253, 253, 253],
         [253, 253, 253],
         [253, 253, 253],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        ...,

        [[255, 255, 255],
         [255, 255, 255],
         [254, 254, 254],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]]], shape=(1316, 2978, 3), dtype=uint8)
 orig_shape: (1316, 2978)
 path: 'image8.jpg'
 probs: None
 save_dir: '/kaggle/working/predictions/disease_sample'
 semantic_mask: None
 speed: {'preprocess': 5.556212699957541, 'inference': 23.642169300001115, 'postprocess': 0.8009758999833139},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'Impacted', 1: 'Caries', 2: 'Periapical_Lesion', 3: 'Deep_Caries'}
 obb: None
 orig_img: array([[[254, 254, 254],
         [254, 254, 254],
         [254, 254, 254],
         ...,
         [255, 255, 255],
         [254, 254, 254],
         [254, 254, 254]],

        [[254, 254, 254],
         [254, 254, 254],
         [254, 254, 254],
         ...,
         [255, 255, 255],
         [254, 254, 254],
         [253, 253, 253]],

        [[253, 253, 253],
         [253, 253, 253],
         [253, 253, 253],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [254, 254, 254]],

        ...,

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [253, 253, 253],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [254, 254, 254],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]]], shape=(1316, 2772, 3), dtype=uint8)
 orig_shape: (1316, 2772)
 path: 'image9.jpg'
 probs: None
 save_dir: '/kaggle/working/predictions/disease_sample'
 semantic_mask: None
 speed: {'preprocess': 5.556212699957541, 'inference': 23.642169300001115, 'postprocess': 0.8009758999833139}]

In [28]:
print("FDI predictions:")
!ls -lah /kaggle/working/predictions/fdi_sample

print("Disease predictions:")
!ls -lah /kaggle/working/predictions/disease_sample

FDI predictions:
total 9.6M
drwxr-xr-x 2 root root 4.0K Jun 30 11:31 .
drwxr-xr-x 4 root root 4.0K Jun 30 11:31 ..
-rw-r--r-- 1 root root 837K Jun 30 11:31 image0.jpg
-rw-r--r-- 1 root root 1.1M Jun 30 11:31 image1.jpg
-rw-r--r-- 1 root root 1.2M Jun 30 11:31 image2.jpg
-rw-r--r-- 1 root root 1.1M Jun 30 11:31 image3.jpg
-rw-r--r-- 1 root root 799K Jun 30 11:31 image4.jpg
-rw-r--r-- 1 root root 1.1M Jun 30 11:31 image5.jpg
-rw-r--r-- 1 root root 993K Jun 30 11:31 image6.jpg
-rw-r--r-- 1 root root 885K Jun 30 11:31 image7.jpg
-rw-r--r-- 1 root root 996K Jun 30 11:31 image8.jpg
-rw-r--r-- 1 root root 967K Jun 30 11:31 image9.jpg
Disease predictions:
total 9.8M
drwxr-xr-x 2 root root  4.0K Jun 30 11:31 .
drwxr-xr-x 4 root root  4.0K Jun 30 11:31 ..
-rw-r--r-- 1 root root  834K Jun 30 11:31 image0.jpg
-rw-r--r-- 1 root root  1.2M Jun 30 11:31 image1.jpg
-rw-r--r-- 1 root root  1.2M Jun 30 11:31 image2.jpg
-rw-r--r-- 1 root root  1.1M Jun 30 11:31 image3.jpg
-rw-r--r-- 1 root root  795K Jun 30 11:31 image4.jpg
-rw-r--r-- 1 root root  1.1M Jun 30 11:31 image5.jpg
-rw-r--r-- 1 root root  1.1M Jun 30 11:31 image6.jpg
-rw-r--r-- 1 root root  930K Jun 30 11:31 image7.jpg
-rw-r--r-- 1 root root 1019K Jun 30 11:31 image8.jpg
-rw-r--r-- 1 root root  971K Jun 30 11:31 image9.jpg

In [29]:
from ultralytics import YOLO
import shutil
from pathlib import Path

FDI_BEST = "/kaggle/working/runs/dentex_fdi_v1-2/weights/best.pt"
DISEASE_BEST = "/kaggle/working/runs/dentex_disease_v1-3/weights/best.pt"

fdi_model = YOLO(FDI_BEST)
disease_model = YOLO(DISEASE_BEST)

print("Export FDI ONNX...")
fdi_model.export(
    format="onnx",
    imgsz=1024,
    simplify=True
)

print("Export disease ONNX...")
disease_model.export(
    format="onnx",
    imgsz=1024,
    simplify=True
)

Export FDI ONNX...
Ultralytics 8.4.83 🚀 Python-3.12.13 torch-2.10.0+cu128 CPU (Intel Xeon CPU @ 2.00GHz)
💡 ProTip: Export to OpenVINO format for best performance on Intel hardware. Learn more at https://docs.ultralytics.com/integrations/openvino/
Model summary (fused): 113 layers, 43,631,280 parameters, 0 gradients, 165.0 GFLOPs

PyTorch: starting from '/kaggle/working/runs/dentex_fdi_v1-2/weights/best.pt' with input shape (1, 3, 1024, 1024) BCHW and output shape(s) (1, 36, 21504) (83.7 MB)
requirements: Ultralytics requirements ['onnxruntime', 'onnxslim>=0.1.82'] not found, attempting AutoUpdate...
Using Python 3.12.13 environment at: /usr
Resolved 12 packages in 462ms
Prepared 2 packages in 395ms
Installed 2 packages in 41ms
 + onnxruntime==1.27.0
 + onnxslim==0.1.94

requirements: AutoUpdate success ✅ 1.7s
WARNING ⚠️ requirements: Restart runtime or rerun command for updates to take effect


ONNX: starting export with onnx 1.21.0 opset 20...
ONNX: slimming with onnxslim 0.1.94...
ONNX: export success ✅ 9.0s, saved as '/kaggle/working/runs/dentex_fdi_v1-2/weights/best.onnx' (167.0 MB)

Export complete (15.5s)
Results saved to /kaggle/working/runs/dentex_fdi_v1-2/weights/best.onnx
Predict:         yolo predict task=detect model=/kaggle/working/runs/dentex_fdi_v1-2/weights/best.onnx imgsz=1024
Validate:        yolo val task=detect model=/kaggle/working/runs/dentex_fdi_v1-2/weights/best.onnx imgsz=1024 data=/kaggle/working/fdi.yaml
Visualize:       https://netron.app
Export disease ONNX...
Ultralytics 8.4.83 🚀 Python-3.12.13 torch-2.10.0+cu128 CPU (Intel Xeon CPU @ 2.00GHz)
Model summary (fused): 73 layers, 11,127,132 parameters, 0 gradients, 28.4 GFLOPs

PyTorch: starting from '/kaggle/working/runs/dentex_disease_v1-3/weights/best.pt' with input shape (1, 3, 1024, 1024) BCHW and output shape(s) (1, 8, 21504) (21.5 MB)

ONNX: starting export with onnx 1.21.0 opset 20...
ONNX: slimming with onnxslim 0.1.94...
ONNX: export success ✅ 2.1s, saved as '/kaggle/working/runs/dentex_disease_v1-3/weights/best.onnx' (42.9 MB)

Export complete (3.7s)
Results saved to /kaggle/working/runs/dentex_disease_v1-3/weights/best.onnx
Predict:         yolo predict task=detect model=/kaggle/working/runs/dentex_disease_v1-3/weights/best.onnx imgsz=1024
Validate:        yolo val task=detect model=/kaggle/working/runs/dentex_disease_v1-3/weights/best.onnx imgsz=1024 data=/kaggle/working/disease.yaml
Visualize:       https://netron.app

'/kaggle/working/runs/dentex_disease_v1-3/weights/best.onnx'

In [30]:
from pathlib import Path

onnx_files = list(Path("/kaggle/working/runs").glob("**/*.onnx"))

for p in onnx_files:
    print(p, "|", round(p.stat().st_size / 1024 / 1024, 2), "MB")

/kaggle/working/runs/dentex_disease_v1-3/weights/best.onnx | 42.93 MB
/kaggle/working/runs/dentex_fdi_v1-2/weights/best.onnx | 166.96 MB

In [31]:
import shutil
from pathlib import Path

EXPORT = Path("/kaggle/working/dentalcare_models")
EXPORT.mkdir(exist_ok=True)

shutil.copy2(
    "/kaggle/working/runs/dentex_fdi_v1-2/weights/best.onnx",
    EXPORT / "dentex_fdi_v1.onnx"
)

shutil.copy2(
    "/kaggle/working/runs/dentex_disease_v1-3/weights/best.onnx",
    EXPORT / "dentex_disease_v1.onnx"
)

print("Contenuto export:")

for f in EXPORT.iterdir():
    print(f.name, round(f.stat().st_size/1024/1024,2),"MB")

Contenuto export:
dentex_fdi_v1.onnx 166.96 MB
dentex_disease_v1.onnx 42.93 MB

In [32]:
import onnx

for model in [
    "/kaggle/working/dentalcare_models/dentex_fdi_v1.onnx",
    "/kaggle/working/dentalcare_models/dentex_disease_v1.onnx"
]:
    m = onnx.load(model)
    onnx.checker.check_model(m)

    print(model)
    print("OK")

/kaggle/working/dentalcare_models/dentex_fdi_v1.onnx
OK
/kaggle/working/dentalcare_models/dentex_disease_v1.onnx
OK

In [33]:
import onnx

for model in [
    "/kaggle/working/dentalcare_models/dentex_fdi_v1.onnx",
    "/kaggle/working/dentalcare_models/dentex_disease_v1.onnx"
]:
    m = onnx.load(model)
    onnx.checker.check_model(m)
    print(model, "OK")

/kaggle/working/dentalcare_models/dentex_fdi_v1.onnx OK
/kaggle/working/dentalcare_models/dentex_disease_v1.onnx OK

In [34]:
import onnxruntime as ort

for model in [
    "/kaggle/working/dentalcare_models/dentex_fdi_v1.onnx",
    "/kaggle/working/dentalcare_models/dentex_disease_v1.onnx"
]:
    sess = ort.InferenceSession(model)

    print("\nMODELLO:", model)

    print("INPUT")
    for i in sess.get_inputs():
        print(i.name, i.shape, i.type)

    print("\nOUTPUT")
    for o in sess.get_outputs():
        print(o.name, o.shape, o.type)

MODELLO: /kaggle/working/dentalcare_models/dentex_fdi_v1.onnx
INPUT
images [1, 3, 1024, 1024] tensor(float)

OUTPUT
output0 [1, 36, 21504] tensor(float)

MODELLO: /kaggle/working/dentalcare_models/dentex_disease_v1.onnx
INPUT
images [1, 3, 1024, 1024] tensor(float)

OUTPUT
output0 [1, 8, 21504] tensor(float)

In [35]:
import json, shutil, os
from pathlib import Path

EXPORT_DIR = Path("/kaggle/working/dentalcare_final_export")
EXPORT_DIR.mkdir(exist_ok=True)

FDI_PT = "/kaggle/working/runs/dentex_fdi_v1-2/weights/best.pt"
DISEASE_PT = "/kaggle/working/runs/dentex_disease_v1-3/weights/best.pt"

files = {
    "dentex_fdi_v1.onnx": "/kaggle/working/dentalcare_models/dentex_fdi_v1.onnx",
    "dentex_disease_v1.onnx": "/kaggle/working/dentalcare_models/dentex_disease_v1.onnx",
    "dentex_fdi_v1.pt": FDI_PT,
    "dentex_disease_v1.pt": DISEASE_PT,
    "fdi.yaml": "/kaggle/working/fdi.yaml",
    "disease.yaml": "/kaggle/working/disease.yaml",
}

for dst_name, src in files.items():
    shutil.copy2(src, EXPORT_DIR / dst_name)

metadata = {
    "project": "DentalCare",
    "models": {
        "fdi": {
            "name": "dentex_fdi_v1",
            "input": [1, 3, 1024, 1024],
            "output": [1, 36, 21504],
            "classes": 32
        },
        "disease": {
            "name": "dentex_disease_v1",
            "input": [1, 3, 1024, 1024],
            "output": [1, 8, 21504],
            "classes": {
                "0": "Impacted",
                "1": "Caries",
                "2": "Periapical_Lesion",
                "3": "Deep_Caries"
            }
        }
    }
}

with open(EXPORT_DIR / "metadata.json", "w") as f:
    json.dump(metadata, f, indent=2)

print("Export folder:")
for p in EXPORT_DIR.iterdir():
    print(p.name, round(p.stat().st_size / 1024 / 1024, 2), "MB")

Export folder:
dentex_fdi_v1.onnx 166.96 MB
dentex_disease_v1.onnx 42.93 MB
disease.yaml 0.0 MB
fdi.yaml 0.0 MB
metadata.json 0.0 MB
dentex_disease_v1.pt 21.51 MB
dentex_fdi_v1.pt 83.66 MB

In [36]:
!zip -r /kaggle/working/dentalcare_final_export.zip /kaggle/working/dentalcare_final_export

  adding: kaggle/working/dentalcare_final_export/ (stored 0%)
  adding: kaggle/working/dentalcare_final_export/dentex_fdi_v1.onnx (deflated 18%)
  adding: kaggle/working/dentalcare_final_export/dentex_disease_v1.onnx (deflated 16%)
  adding: kaggle/working/dentalcare_final_export/disease.yaml (deflated 22%)
  adding: kaggle/working/dentalcare_final_export/fdi.yaml (deflated 52%)
  adding: kaggle/working/dentalcare_final_export/metadata.json (deflated 65%)
  adding: kaggle/working/dentalcare_final_export/dentex_disease_v1.pt (deflated 8%)
  adding: kaggle/working/dentalcare_final_export/dentex_fdi_v1.pt (deflated 8%)

In [37]:
from pathlib import Path
import zipfile

zip_path = Path("/kaggle/working/dentalcare_final_export.zip")

print("ZIP esiste:", zip_path.exists())
print("Dimensione ZIP:", round(zip_path.stat().st_size / 1024 / 1024, 2), "MB")

with zipfile.ZipFile(zip_path, "r") as z:
    bad = z.testzip()
    print("Integrità ZIP:", "OK" if bad is None else f"ERRORE su {bad}")
    print("\nContenuto:")
    for name in z.namelist():
        print(name)

ZIP esiste: True
Dimensione ZIP: 270.23 MB
Integrità ZIP: OK

Contenuto:
kaggle/working/dentalcare_final_export/
kaggle/working/dentalcare_final_export/dentex_fdi_v1.onnx
kaggle/working/dentalcare_final_export/dentex_disease_v1.onnx
kaggle/working/dentalcare_final_export/disease.yaml
kaggle/working/dentalcare_final_export/fdi.yaml
kaggle/working/dentalcare_final_export/metadata.json
kaggle/working/dentalcare_final_export/dentex_disease_v1.pt
kaggle/working/dentalcare_final_export/dentex_fdi_v1.pt

In [38]:
from ultralytics import YOLO
from pathlib import Path

img = str(sorted(Path("/kaggle/working/dentex_disease_yolo/images/val").glob("*"))[0])

print(img)

pt_model = YOLO("/kaggle/working/runs/dentex_disease_v1-3/weights/best.pt")
onnx_model = YOLO("/kaggle/working/dentalcare_models/dentex_disease_v1.onnx")

pt_result = pt_model.predict(
    source=img,
    imgsz=1024,
    conf=0.25,
    verbose=False
)

onnx_result = onnx_model.predict(
    source=img,
    imgsz=1024,
    conf=0.25,
    verbose=False
)

print("PT detections :", len(pt_result[0].boxes))
print("ONNX detections:", len(onnx_result[0].boxes))

/kaggle/working/dentex_disease_yolo/images/val/train_127.png
WARNING ⚠️ Unable to automatically guess model task, assuming 'task=detect'. Explicitly define task for your model, i.e. 'task=detect', 'segment', 'classify', 'pose', 'obb' or 'semantic'.
Loading /kaggle/working/dentalcare_models/dentex_disease_v1.onnx for ONNX Runtime inference...
requirements: Ultralytics requirement ['onnxruntime-gpu'] not found, attempting AutoUpdate...
Using Python 3.12.13 environment at: /usr
Resolved 5 packages in 311ms
Prepared 1 package in 1.93s
Installed 1 package in 121ms
 + onnxruntime-gpu==1.27.0

requirements: AutoUpdate success ✅ 2.5s
WARNING ⚠️ requirements: Restart runtime or rerun command for updates to take effect

WARNING ⚠️ CUDA requested but CUDAExecutionProvider not available. Using CPU...
Using ONNX Runtime 1.27.0 with CPUExecutionProvider
PT detections : 2
ONNX detections: 2

In [39]:
import pandas as pd

def boxes_to_df(result):
    boxes = result[0].boxes
    rows = []

    for i in range(len(boxes)):
        xyxy = boxes.xyxy[i].cpu().numpy().tolist()
        cls = int(boxes.cls[i].cpu().numpy())
        conf = float(boxes.conf[i].cpu().numpy())

        rows.append({
            "class_id": cls,
            "confidence": round(conf, 4),
            "x1": round(xyxy[0], 1),
            "y1": round(xyxy[1], 1),
            "x2": round(xyxy[2], 1),
            "y2": round(xyxy[3], 1),
        })

    return pd.DataFrame(rows)

pt_df = boxes_to_df(pt_result)
onnx_df = boxes_to_df(onnx_result)

print("PT")
display(pt_df)

print("ONNX")
display(onnx_df)

PT

   class_id  confidence      x1     y1      x2     y2
0         1      0.8367   656.3  687.4   899.1  951.7
1         1      0.3163  1820.0  449.9  1961.4  746.1

ONNX

   class_id  confidence      x1     y1      x2     y2
0         1      0.8307   656.0  687.1   899.3  953.6
1         1      0.3313  1819.9  451.5  1961.4  745.9